/**
 * charts-contrast.test.ts — deterministic, browser-free WCAG gate on the chart
 * palette (`--chart-1..5` + chart text/label tokens) across all themes.
 *
 * Sibling to themes-contrast.test.ts (CH-01 #113, the theme AA audit). It
 * parses themes.css, extracts each theme's chart tokens (resolving `var(--x)`
 * aliases — `--chart-background` is `var(--card)`, `--chart-foreground` is
 * `var(--foreground)`, …), and asserts:
 *   - series colors `--chart-1..5` clear the WCAG 1.4.11 non-text bar (≥ 3:1)
 *     against the chart surface they render on (`--chart-background`), so a bar /
 *     line / point is visible on its own;
 *   - chart text `--chart-foreground` / `--chart-label` clears AA body text
 *     (≥ 4.5:1) and muted chart text `--chart-foreground-muted` clears ≥ 3:1.
 *
 * The committed, human-readable evidence for these assertions lives in
 * `apps/e2e/reports/theme-aa-audit.md`, generated by `pnpm audit-artifact` and
 * stale-gated by `pnpm audit-artifact:check` (#78). This file used to write its
 * own `AUDIT_WRITE=1`-gated artifact; that was an opt-in reminder, not a gate,
 * and the file it produced still documented two deleted themes months later.
 */
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { describe, expect, it } from "vitest";
import { contrast } from "./color-contrast";

const __dirname = dirname(fileURLToPath(import.meta.url));
const css = readFileSync(join(__dirname, "themes.css"), "utf8");

/** WCAG thresholds. */
const AA_TEXT = 4.5; // body text
const NON_TEXT = 3.0; // graphical objects / UI components (1.4.11) + secondary text

function extractBlock(re: RegExp): string {
  const m = css.match(re);
  const body = m?.[1];
  if (body == null) throw new Error(`Block not found for ${re}`);
  return body;
}
function extractThemeBlock(name: string): string {
  return extractBlock(new RegExp(`\\[data-theme="${name}"\\]\\s*\\{([\\s\\S]*?)\\n\\}`));
}
const THEME_BLOCKS: Record<string, string> = {
  light: extractBlock(/:root\s*\{([\s\S]*?)\n\}/),
  "qlik-bright": extractThemeBlock("qlik-bright"),
  "qlik-dark": extractThemeBlock("qlik-dark"),
};

/**
 * Blank out CSS comments, preserving length and newlines. `themes.css`
 * documents the very tokens this scanner parses, so a comment sitting
 * directly above a declaration routinely contains a `--token:`-shaped
 * substring (e.g. the real comment above qlik-bright's `--ring`, which
 * mentions `--info:`). Without blanking, the lazy `[^;]+` below can start a
 * match INSIDE that comment and run to the semicolon of the NEXT real
 * declaration, silently dropping it (#401 — the same hazard
 * `scripts/check-elevation.mjs`'s `blankComments` was written to fix, and the
 * same fix already applied in `scripts/check-role-distinctness.mjs`).
 * Duplicated locally (rather than imported across the packages/tokens ⇄
 * repo-root `scripts/` boundary) to avoid pulling a `.test.ts` outside its
 * package's TS `rootDir`.
 */
function blankComments(cssText: string): string {
  return cssText.replace(/\/\*[\s\S]*?\*\//g, (m) => m.replace(/[^\n]/g, " "));
}

/** All `--token: <value>;` declarations (oklch OR var(...)) → map. */
function tokenMap(body: string): Record<string, string> {
  const map: Record<string, string> = {};
  for (const m of blankComments(body).matchAll(/(--[\w-]+):\s*([^;]+);/g)) {
    if (m[1] && m[2]) map[m[1]] = m[2].trim();
  }
  return map;
}
const TOKENS: Record<string, Record<string, string>> = Object.fromEntries(
  Object.entries(THEME_BLOCKS).map(([n, b]) => [n, tokenMap(b)]),
);
const THEMES = Object.keys(THEME_BLOCKS);
const SERIES = ["--chart-1", "--chart-2", "--chart-3", "--chart-4", "--chart-5"] as const;

/** Resolve a token to a concrete `oklch(...)` literal, following `var(--x)`
 *  aliases within the theme (then the light/:root base as fallback). */
function resolve(theme: string, name: string, seen: string[] = []): string {
  if (seen.includes(name)) throw new Error(`var() cycle: ${seen.join(" → ")} → ${name}`);
  const raw = TOKENS[theme]?.[name] ?? TOKENS.light?.[name];
  if (!raw) throw new Error(`${theme} is missing ${name} (and no :root fallback)`);
  const varMatch = raw.match(/^var\(\s*(--[\w-]+)\s*\)$/);
  if (varMatch?.[1]) return resolve(theme, varMatch[1], [...seen, name]);
  if (!raw.startsWith("oklch(")) throw new Error(`${theme} ${name} is not oklch/var: ${raw}`);
  return raw;
}

describe("themes.css — chart palette WCAG contrast (all themes)", () => {
  describe.each(THEMES)("%s", (theme) => {
    it.each(SERIES)("%s ≥ 3:1 on --chart-background", (s) => {
      const ratio = contrast(resolve(theme, s), resolve(theme, "--chart-background"));
      expect(
        ratio,
        `${s} vs --chart-background in ${theme} = ${ratio.toFixed(2)}`,
      ).toBeGreaterThanOrEqual(NON_TEXT);
    });
    it("--chart-foreground ≥ 4.5:1 on --chart-background", () => {
      const ratio = contrast(
        resolve(theme, "--chart-foreground"),
        resolve(theme, "--chart-background"),
      );
      expect(ratio, `--chart-foreground in ${theme} = ${ratio.toFixed(2)}`).toBeGreaterThanOrEqual(
        AA_TEXT,
      );
    });
    it("--chart-label ≥ 4.5:1 on --chart-background", () => {
      const ratio = contrast(resolve(theme, "--chart-label"), resolve(theme, "--chart-background"));
      expect(ratio, `--chart-label in ${theme} = ${ratio.toFixed(2)}`).toBeGreaterThanOrEqual(
        AA_TEXT,
      );
    });
    it("--chart-foreground-muted ≥ 3:1 on --chart-background", () => {
      const ratio = contrast(
        resolve(theme, "--chart-foreground-muted"),
        resolve(theme, "--chart-background"),
      );
      expect(
        ratio,
        `--chart-foreground-muted in ${theme} = ${ratio.toFixed(2)}`,
      ).toBeGreaterThanOrEqual(NON_TEXT);
    });
  });
});

// NOTE Issue #163's monochrome chart-series lightness ramp lived here. It only
// applied to the PAUSED `blueprint` theme, so it is retired with it — restore it
// from git history when that theme is un-paused (.claude/rules/paused-surfaces.md).

// #401 — `tokenMap` (above) used to scan the RAW block body: a comment sitting
// directly above a declaration and mentioning a `--token:`-shaped substring
// (themes.css documents its own tokens inline, e.g. the real comment above
// qlik-bright's `--ring`) made the lazy `[^;]+` regex start matching INSIDE
// the comment and consume through to the semicolon of the NEXT real
// declaration, silently dropping it. Same class of bug already fixed in
// `scripts/check-role-distinctness.mjs` (commit 22ca442).
describe("tokenMap — comment blindness (#401)", () => {
  it("does not swallow a declaration preceded by a comment mentioning another --token:", () => {
    const body = `
  /* mentions --other-token: in prose here, not a real declaration */
  --chart-1: oklch(0.55 0.2 300);
`;
    const map = tokenMap(body);
    expect(map["--chart-1"]).toBe("oklch(0.55 0.2 300)");
    expect(map["--other-token"]).toBeUndefined();
  });
});
