/**
 * charts-contrast.test.ts — deterministic, browser-free WCAG gate on the chart
 * palette (`--chart-1..12` + chart text/label tokens) across all themes.
 *
 * Sibling to themes-contrast.test.ts (CH-01 #113, the theme AA audit). It
 * parses themes.css, extracts each theme's chart tokens (resolving `var(--x)`
 * aliases — `--chart-background` is `var(--card)`, `--chart-foreground` is
 * `var(--foreground)`, …), and asserts:
 *   - series colors `--chart-1..12` clear the WCAG 1.4.11 non-text bar (≥ 3:1)
 *     against the chart surface they render on (`--chart-background`), so a bar /
 *     line / point is visible on its own;
 *   - chart text `--chart-foreground` / `--chart-label` clears AA body text
 *     (≥ 4.5:1) and muted chart text `--chart-foreground-muted` clears ≥ 3:1.
 *
 * The committed, human-readable evidence for these assertions lives in
 * `apps/e2e/reports/theme-aa-audit.md`, generated by `pnpm audit-artifact` and
 * stale-gated by `pnpm audit-artifact:check` (#78). This file used to write its
 * own `AUDIT_WRITE=1`-gated artifact; that was an opt-in reminder, not a gate,
 * and the file it produced still documented two deleted themes months later.
 */
import { describe, expect, it } from "vitest";

import { readThemeCss } from "./_theme-css-source";
import { contrast, contrastSrgb, mixOverSrgb, parseOklch } from "./color-contrast";

// ADR 0029 — the reference themes live in their own stylesheets now, so read
// the SET. The helper throws if a theme's block is missing rather than let a
// block regex match less and pass vacuously.
const css = readThemeCss();

/** WCAG thresholds. */
const AA_TEXT = 4.5; // body text
const NON_TEXT = 3.0; // graphical objects / UI components (1.4.11) + secondary text

function extractBlock(re: RegExp): string {
  const m = css.match(re);
  const body = m?.[1];
  if (body == null) throw new Error(`Block not found for ${re}`);
  return body;
}
function extractThemeBlock(name: string): string {
  return extractBlock(new RegExp(`\\[data-theme="${name}"\\]\\s*\\{([\\s\\S]*?)\\n\\}`));
}
/**
 * `root` is the `:root` neutral base/fallback — NOT a selectable theme, and
 * deliberately NOT keyed `light`: `light` is a real shipped theme slug, and a
 * colliding key silently overwrote the base block here. See themes-contrast.test.ts.
 */
const THEME_BLOCKS: Record<string, string> = {
  root: extractBlock(/:root\s*\{([\s\S]*?)\n\}/),
  light: extractThemeBlock("light"),
  dark: extractThemeBlock("dark"),
};

/**
 * Blank out CSS comments, preserving length and newlines. `themes.css`
 * documents the very tokens this scanner parses, so a comment sitting
 * directly above a declaration routinely contains a `--token:`-shaped
 * substring (e.g. the real comment above light's `--ring`, which
 * mentions `--info:`). Without blanking, the lazy `[^;]+` below can start a
 * match INSIDE that comment and run to the semicolon of the NEXT real
 * declaration, silently dropping it (#401 — the same hazard
 * `scripts/check-elevation.mjs`'s `blankComments` was written to fix, and the
 * same fix already applied in `scripts/check-role-distinctness.mjs`).
 * Duplicated locally (rather than imported across the packages/tokens ⇄
 * repo-root `scripts/` boundary) to avoid pulling a `.test.ts` outside its
 * package's TS `rootDir`.
 */
function blankComments(cssText: string): string {
  return cssText.replace(/\/\*[\s\S]*?\*\//g, (m) => m.replace(/[^\n]/g, " "));
}

/** All `--token: <value>;` declarations (oklch OR var(...)) → map. */
function tokenMap(body: string): Record<string, string> {
  const map: Record<string, string> = {};
  for (const m of blankComments(body).matchAll(/(--[\w-]+):\s*([^;]+);/g)) {
    if (m[1] && m[2]) map[m[1]] = m[2].trim();
  }
  return map;
}
const TOKENS: Record<string, Record<string, string>> = Object.fromEntries(
  Object.entries(THEME_BLOCKS).map(([n, b]) => [n, tokenMap(b)]),
);
const THEMES = Object.keys(THEME_BLOCKS);
/**
 * All twelve categorical series. The ramp grew 5 → 12 on 2026-08-16; every new
 * member is gated on the same 1.4.11 bar as the original five, which is what
 * forced `--chart-11` (authored `#434C57`, 1.84:1 on the dark card) up a rung —
 * see the note on that token in `themes/dark.css`.
 */
const SERIES = [
  "--chart-1",
  "--chart-2",
  "--chart-3",
  "--chart-4",
  "--chart-5",
  "--chart-6",
  "--chart-7",
  "--chart-8",
  "--chart-9",
  "--chart-10",
  "--chart-11",
  "--chart-12",
] as const;

/** Resolve a token to a concrete `oklch(...)` literal, following `var(--x)`
 *  aliases within the theme (then the `root`/`:root` base as fallback). */
function resolve(theme: string, name: string, seen: string[] = []): string {
  if (seen.includes(name)) throw new Error(`var() cycle: ${seen.join(" → ")} → ${name}`);
  const raw = TOKENS[theme]?.[name] ?? TOKENS.root?.[name];
  if (!raw) throw new Error(`${theme} is missing ${name} (and no :root fallback)`);
  const varMatch = raw.match(/^var\(\s*(--[\w-]+)\s*\)$/);
  if (varMatch?.[1]) return resolve(theme, varMatch[1], [...seen, name]);
  if (!raw.startsWith("oklch(")) throw new Error(`${theme} ${name} is not oklch/var: ${raw}`);
  return raw;
}

/**
 * Themes whose SERIES ramp is exempt from the ≥3:1 1.4.11 mark bar.
 *
 * `light` only, and it is a signed-off regression decided 2026-08-16, not an
 * oversight: the authored twelve-colour palette is tuned for a mid/dark plot
 * ground, and the maintainer chose to ship it verbatim in BOTH reference themes
 * rather than keep the re-tuned light ramp that satisfied this bar and read as
 * mud. Nine of the twelve measure under 3:1 on this theme's white
 * `--chart-background` (worst: `--chart-10` at 1.22:1). Full measurements and
 * the systemic repair (darken the plot ground, not the palette) are recorded on
 * the ramp in `themes/light.css`.
 *
 * The exemption is NOT a hole: the exempt branch below asserts the ramp is still
 * value-identical to `dark`'s, so a later re-tune of the light ramp — the exact
 * change that would make this exemption stale — fails the suite instead of
 * passing quietly. `:root` is deliberately NOT exempt; it keeps its own
 * compliant ramp so a consumer who imports no theme stylesheet still gets
 * legible charts.
 *
 * `--chart-accent` (RM-018's "wire" palette hero colour) is COVERED BY THIS SAME
 * SET, not a second exemption — decided 2026-09-04 (#179). It is declared
 * `var(--chart-1)` (see the "--chart-accent mirrors --chart-1" test below), so
 * it is `--chart-1` under a second name and inherits `CHART_1411_EXEMPT`
 * automatically; there is nothing to add here. What #179 is about is the
 * SURFACE, not the token: the accent palette's premise is "one hero colour,
 * loudest mark on the plot", and on `light` it measures 1.42:1 against
 * `--chart-background`/`--card` — quieter than its usual "wire" companions
 * `--chart-mono-2`/`-4`/`-6` (3.10 / 5.70 / 10.21:1) and quieter than the
 * sequential ramp's own declared quiet step `--chart-seq-1` (1.62:1). Declined
 * repairs (darken `--chart-background`; derive a per-theme accent) and the full
 * cost are recorded in `.claude/rules/theming.md` beside this bullet's sibling.
 * No assertion is added for it: a gate requiring the accent not be the
 * lowest-contrast member of its palette would fail by design on `light` — see
 * issue #179's revised acceptance.
 */
const CHART_1411_EXEMPT = new Set(["light"]);

describe("themes.css — chart palette WCAG contrast (all themes)", () => {
  describe.each(THEMES)("%s", (theme) => {
    if (CHART_1411_EXEMPT.has(theme)) {
      it.each(SERIES)("%s mirrors the dark ramp (1.4.11 exemption)", (s) => {
        expect(
          resolve(theme, s),
          `${s}: the ${theme} exemption is only valid while its ramp IS dark's`,
        ).toBe(resolve("dark", s));
      });
      it("is still below the 3:1 bar (delete the exemption once it is not)", () => {
        const failing = SERIES.filter(
          (s) => contrast(resolve(theme, s), resolve(theme, "--chart-background")) < NON_TEXT,
        );
        expect(failing.length, `${theme} series now clearing 3:1: ${failing.length}/12`).toBe(9);
      });
    } else {
      it.each(SERIES)("%s ≥ 3:1 on --chart-background", (s) => {
        const ratio = contrast(resolve(theme, s), resolve(theme, "--chart-background"));
        expect(
          ratio,
          `${s} vs --chart-background in ${theme} = ${ratio.toFixed(2)}`,
        ).toBeGreaterThanOrEqual(NON_TEXT);
      });
    }
    it("--chart-foreground ≥ 4.5:1 on --chart-background", () => {
      const ratio = contrast(
        resolve(theme, "--chart-foreground"),
        resolve(theme, "--chart-background"),
      );
      expect(ratio, `--chart-foreground in ${theme} = ${ratio.toFixed(2)}`).toBeGreaterThanOrEqual(
        AA_TEXT,
      );
    });
    it("--chart-label ≥ 4.5:1 on --chart-background", () => {
      const ratio = contrast(resolve(theme, "--chart-label"), resolve(theme, "--chart-background"));
      expect(ratio, `--chart-label in ${theme} = ${ratio.toFixed(2)}`).toBeGreaterThanOrEqual(
        AA_TEXT,
      );
    });
    it("--chart-foreground-muted ≥ 3:1 on --chart-background", () => {
      const ratio = contrast(
        resolve(theme, "--chart-foreground-muted"),
        resolve(theme, "--chart-background"),
      );
      expect(
        ratio,
        `--chart-foreground-muted in ${theme} = ${ratio.toFixed(2)}`,
      ).toBeGreaterThanOrEqual(NON_TEXT);
    });
  });
});

/**
 * ORDERED RAMPS (RM-018) — the other half of the chart palette.
 *
 * `SERIES` above is CATEGORICAL: twelve colours that answer "which series". The
 * ramps below are ORDINAL — they answer "how much", and the whole contract is
 * that lightness IS the data. That makes them a different gate, not more rows of
 * the same one: a categorical ramp must only be mutually distinct, an ordinal
 * ramp must additionally be MONOTONIC, or a heatmap cell's colour stops meaning
 * its value. Adjacent-step separation (0.05 OKLab ΔE) is the sibling half and
 * lives in `scripts/check-role-distinctness.mjs`, with the twelve categorical
 * rows, rather than being duplicated here.
 */
const SEQ = Array.from({ length: 7 }, (_, i) => `--chart-seq-${i + 1}`);
const MONO = Array.from({ length: 7 }, (_, i) => `--chart-mono-${i + 1}`);
/** Diverging, in RAMP order: far-negative → neutral → far-positive. */
const DIV = [
  "--chart-div-neg-2",
  "--chart-div-neg-1",
  "--chart-div-mid",
  "--chart-div-pos-1",
  "--chart-div-pos-2",
] as const;
/** Index of the neutral middle in `DIV`. */
const DIV_MID = 2;
/**
 * The QUIET steps — the ONLY members exempt from the 1.4.11 3:1 mark bar, and
 * the exemption is bounded rather than open: they must still clear
 * `QUIET_MIN`, so one low cell in a heatmap reads as a pinprick instead of as
 * blank paper. `--chart-div-mid` is deliberately NOT here: a zero-valued cell
 * in a diverging chart is still a drawn cell that has to be told from the plot
 * ground.
 */
const QUIET = new Set<string>(["--chart-seq-1", "--chart-mono-1"]);
const QUIET_MIN = 1.5;
/** Max chroma for the neutral ladder — "mono" has to actually read as neutral. */
const MONO_MAX_CHROMA = 0.02;

/** The OKLab L of a resolved `oklch(...)` literal. */
function lightnessOf(theme: string, token: string): number {
  return parseOklch(resolve(theme, token)).l;
}
function chromaOf(theme: string, token: string): number {
  return parseOklch(resolve(theme, token)).c;
}

describe("themes.css — ordered chart ramps (RM-018)", () => {
  // Anti-vacuity: every assertion below is a `.each` over these lists, so an
  // empty/typo'd list would make the whole block pass without measuring a thing.
  it("gates three ramps of the expected length", () => {
    expect([SEQ.length, MONO.length, DIV.length]).toEqual([7, 7, 5]);
  });

  describe.each(THEMES)("%s", (theme) => {
    it.each([...SEQ, ...MONO, ...DIV])("%s clears its contrast bar", (token) => {
      const ratio = contrast(resolve(theme, token), resolve(theme, "--chart-background"));
      const bar = QUIET.has(token) ? QUIET_MIN : NON_TEXT;
      expect(
        ratio,
        `${token} vs --chart-background in ${theme} = ${ratio.toFixed(2)} (bar ${bar})`,
      ).toBeGreaterThanOrEqual(bar);
    });

    // MONOTONIC, stated twice on purpose. OKLab L is the authored dimension —
    // "lightness is data" — and contrast-against-the-ground is what the reader
    // actually perceives. They can come apart at high chroma, and a ramp that is
    // monotonic in one but not the other is a ramp whose steps read out of
    // order. Note the DIRECTION is not asserted: it is a property of the theme's
    // ground (darker = more intense on a white plot ground, lighter on a dark
    // one), so the invariant is monotonicity, not a sign.
    it.each([
      ["sequential", SEQ],
      ["mono", MONO],
    ] as const)("the %s ramp is strictly monotonic in OKLab L", (_name, ramp) => {
      const ls = ramp.map((t) => lightnessOf(theme, t));
      const rising = ls.every((l, i) => i === 0 || l > (ls[i - 1] as number));
      const falling = ls.every((l, i) => i === 0 || l < (ls[i - 1] as number));
      expect(rising || falling, `${theme} L: ${ls.map((l) => l.toFixed(3)).join(" → ")}`).toBe(
        true,
      );
    });

    it.each([
      ["sequential", SEQ],
      ["mono", MONO],
    ] as const)("the %s ramp gains contrast with every step", (_name, ramp) => {
      const bg = resolve(theme, "--chart-background");
      const rs = ramp.map((t) => contrast(resolve(theme, t), bg));
      expect(
        rs.every((r, i) => i === 0 || r > (rs[i - 1] as number)),
        `${theme}: ${rs.map((r) => r.toFixed(2)).join(" → ")}`,
      ).toBe(true);
    });

    // The diverging ramp is a V, not a run: intensity has to grow from the
    // neutral middle outward along BOTH arms, or "strongly negative" reads
    // quieter than "slightly negative".
    it("the diverging ramp gains contrast from the mid outward on both arms", () => {
      const bg = resolve(theme, "--chart-background");
      const rs = DIV.map((t) => contrast(resolve(theme, t), bg));
      for (let i = DIV_MID; i > 0; i--) {
        expect(
          rs[i - 1] as number,
          `${theme} ${DIV[i - 1]} vs ${DIV[i]}: ${rs.map((r) => r.toFixed(2)).join(" ")}`,
        ).toBeGreaterThan(rs[i] as number);
      }
      for (let i = DIV_MID; i < DIV.length - 1; i++) {
        expect(
          rs[i + 1] as number,
          `${theme} ${DIV[i + 1]} vs ${DIV[i]}: ${rs.map((r) => r.toFixed(2)).join(" ")}`,
        ).toBeGreaterThan(rs[i] as number);
      }
    });

    it.each(MONO)("%s is neutral (chroma ≤ 0.02)", (token) => {
      const c = chromaOf(theme, token);
      expect(c, `${token} in ${theme} has chroma ${c}`).toBeLessThanOrEqual(MONO_MAX_CHROMA);
    });

    // `--chart-accent` is the wire palette's one hero colour and is declared as
    // `var(--chart-1)` so a re-brand reaches it for free (#385 — an intentional
    // mirror is a `var()`, never a copied literal). Asserted as an EQUALITY of
    // resolved values, so replacing the alias with today's literal fails here.
    // Because the equality holds, `--chart-accent` also inherits `CHART_1411_EXEMPT`
    // on `light` for free — see the comment on that set (#179) for the accent
    // palette's own cost, which is sharper than the categorical ramp's.
    it("--chart-accent mirrors --chart-1", () => {
      expect(TOKENS[theme]?.["--chart-accent"]).toBe("var(--chart-1)");
      expect(resolve(theme, "--chart-accent")).toBe(resolve(theme, "--chart-1"));
    });
  });
});

/**
 * CanvasLayer reference-story full-density mark ink (#283).
 *
 * A canvas `draw` composites its own pixels — nothing downstream can read a
 * bitmap, so this pins the ink the shipped `canvas-layer.stories.tsx`
 * reference wiring actually uses at the alpha it actually uses it at, rather
 * than trusting the recommendation once. It is NOT a general canvas-ink
 * gate: an arbitrary consumer's `draw` is unchecked by anything in this repo
 * (that is what `canvas-layer.tsx`'s docblock §4 and the "Canvas mark ink is
 * the caller's own compliance" note in `.claude/rules/chart-components.md`
 * are for).
 *
 * `CHART_1411_EXEMPT` does not apply here on purpose: this token is a NEUTRAL
 * mono rung, not a categorical series colour, so it is held to the ordinary
 * 3:1 bar in every theme, `light` included.
 */
describe("CanvasLayer full-density mark ink (#283)", () => {
  /** The alpha `canvas-layer.stories.tsx`'s `DottedCanvas` paints marks at. */
  const CANVAS_MARK_ALPHA = 0.65;

  it.each(THEMES)(
    "--chart-mono-7 composited at α=0.65 over --chart-background ≥ 3:1 in %s",
    (theme) => {
      const ground = parseOklch(resolve(theme, "--chart-background"));
      const ink = parseOklch(resolve(theme, "--chart-mono-7"));
      const composited = mixOverSrgb(ink, ground, CANVAS_MARK_ALPHA);
      const ratio = contrastSrgb(ground, composited);
      expect(
        ratio,
        `--chart-mono-7 @ α=${CANVAS_MARK_ALPHA} vs --chart-background in ${theme} = ${ratio.toFixed(2)}`,
      ).toBeGreaterThanOrEqual(NON_TEXT);
    },
  );
});

// NOTE Issue #163's monochrome chart-series lightness ramp lived here. It only
// applied to a monochrome theme this repo no longer ships, so it is retired with
// it — restore it from git history if such a theme returns.

// #401 — `tokenMap` (above) used to scan the RAW block body: a comment sitting
// directly above a declaration and mentioning a `--token:`-shaped substring
// (themes.css documents its own tokens inline, e.g. the real comment above
// light's `--ring`) made the lazy `[^;]+` regex start matching INSIDE
// the comment and consume through to the semicolon of the NEXT real
// declaration, silently dropping it. Same class of bug already fixed in
// `scripts/check-role-distinctness.mjs` (commit 22ca442).
describe("tokenMap — comment blindness (#401)", () => {
  it("does not swallow a declaration preceded by a comment mentioning another --token:", () => {
    const body = `
  /* mentions --other-token: in prose here, not a real declaration */
  --chart-1: oklch(0.55 0.2 300);
`;
    const map = tokenMap(body);
    expect(map["--chart-1"]).toBe("oklch(0.55 0.2 300)");
    expect(map["--other-token"]).toBeUndefined();
  });
});
