export {
  Card,
  cardVariants,
  type CardProps,
  CardHeader,
  CardTitle,
  type CardTitleProps,
  CardDescription,
  type CardDescriptionProps,
  CardAction,
  CardMedia,
  type CardMediaProps,
  CardContent,
  CardFooter,
} from "./card";
