// GENERATED by scripts/gen-contract-tests.mjs — do not edit; re-run the generator instead.
/**
 * Browser contract probes (axe + horizontal-overflow) for every ai
 * component with a `Default` story, swept over every built-in theme and the
 * phone/tablet/desktop widths. See scripts/gen-contract-tests.mjs.
 */
import { describe, it, expect, afterEach } from "vitest";
import { page } from "@vitest/browser/context";
import { createRoot, type Root } from "react-dom/client";
import { act, type ReactNode } from "react";
import axe from "axe-core";
import { BUILT_IN_THEMES } from "@elabs-ai/components-tokens";
import knownFailuresJson from "../../../scripts/check/contract-known-failures.json";

const KNOWN_FAILURES: Record<string, string> = knownFailuresJson;
const WIDTHS = [375, 768, 1280];

function mountReact(node: ReactNode) {
  const container = document.createElement("div");
  document.body.appendChild(container);
  const root: Root = createRoot(container);
  act(() => {
    root.render(node);
  });
  return {
    container,
    unmount() {
      act(() => {
        root.unmount();
      });
      container.remove();
    },
  };
}

afterEach(() => {
  document.documentElement.removeAttribute("data-theme");
});

/** Wrap a known, tracked failure in `it.fails` so fixing it forces the key's removal. */
function contractIt(
  storyId: string,
  theme: string,
  width: number,
  assertion: string,
  name: string,
  fn: () => void | Promise<void>,
) {
  const key = `${storyId}|${theme}|${width}|${assertion}`;
  const reason = KNOWN_FAILURES[key];
  if (reason) return it.fails(`${name} (known failure: ${reason})`, fn);
  return it(name, fn);
}

// ── AudioVisualizer (packages/ai/src/audio-visualizer.tsx) ────────────────────────────────────────
import * as stories_audio_visualizer from "../../../packages/ai/src/audio-visualizer.stories";
describe("AudioVisualizer contract (browser)", () => {
  const meta = stories_audio_visualizer.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_audio_visualizer as { Default?: { args?: Record<string, unknown> } })
    .Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "ai-audiovisualizer--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "ai-audiovisualizer--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── ChatShell (packages/ai/src/chat-shell.tsx) ────────────────────────────────────────
import * as stories_chat_shell from "../../../packages/ai/src/chat-shell.stories";
describe("ChatShell contract (browser)", () => {
  const meta = stories_chat_shell.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_chat_shell as { Default?: { args?: Record<string, unknown> } }).Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "ai-chatshell--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "ai-chatshell--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── GroupedParts (packages/ai/src/grouped-parts.tsx) ────────────────────────────────────────
import * as stories_grouped_parts from "../../../packages/ai/src/grouped-parts.stories";
describe("GroupedParts contract (browser)", () => {
  const meta = stories_grouped_parts.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_grouped_parts as { Default?: { args?: Record<string, unknown> } })
    .Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "ai-groupedparts--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "ai-groupedparts--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── Image (packages/ai/src/image.tsx) ────────────────────────────────────────
import * as stories_image from "../../../packages/ai/src/image.stories";
describe("Image contract (browser)", () => {
  const meta = stories_image.default as { component?: unknown; args?: Record<string, unknown> };
  const Default = (stories_image as { Default?: { args?: Record<string, unknown> } }).Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt("ai-image--default", theme, width, "axe", "has no axe violations", async () => {
          const { container, unmount } = await mount();
          try {
            const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
            expect(results.violations.map((v) => v.id)).toEqual([]);
          } finally {
            unmount();
          }
        });

        contractIt(
          "ai-image--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── MarkdownView (packages/ai/src/markdown-view.tsx) ────────────────────────────────────────
import * as stories_markdown_view from "../../../packages/ai/src/markdown-view.stories";
describe("MarkdownView contract (browser)", () => {
  const meta = stories_markdown_view.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_markdown_view as { Default?: { args?: Record<string, unknown> } })
    .Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "ai-markdownview--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "ai-markdownview--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── MessageFeedback (packages/ai/src/message-feedback.tsx) ────────────────────────────────────────
import * as stories_message_feedback from "../../../packages/ai/src/message-feedback.stories";
describe("MessageFeedback contract (browser)", () => {
  const meta = stories_message_feedback.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_message_feedback as { Default?: { args?: Record<string, unknown> } })
    .Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "ai-messagefeedback--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "ai-messagefeedback--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── MessageForm (packages/ai/src/message-form.tsx) ────────────────────────────────────────
import * as stories_message_form from "../../../packages/ai/src/message-form.stories";
describe("MessageForm contract (browser)", () => {
  const meta = stories_message_form.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_message_form as { Default?: { args?: Record<string, unknown> } })
    .Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "ai-messageform--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "ai-messageform--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── MessageTable (packages/ai/src/message-table.tsx) ────────────────────────────────────────
import * as stories_message_table from "../../../packages/ai/src/message-table.stories";
describe("MessageTable contract (browser)", () => {
  const meta = stories_message_table.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_message_table as { Default?: { args?: Record<string, unknown> } })
    .Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "ai-messagetable--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "ai-messagetable--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── ModelProviderLogo (packages/ai/src/model-provider-logo.tsx) ────────────────────────────────────────
import * as stories_model_provider_logo from "../../../packages/ai/src/model-provider-logo.stories";
describe("ModelProviderLogo contract (browser)", () => {
  const meta = stories_model_provider_logo.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_model_provider_logo as { Default?: { args?: Record<string, unknown> } })
    .Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "ai-modelproviderlogo--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "ai-modelproviderlogo--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── Persona (packages/ai/src/persona.tsx) ────────────────────────────────────────
import * as stories_persona from "../../../packages/ai/src/persona.stories";
describe("Persona contract (browser)", () => {
  const meta = stories_persona.default as { component?: unknown; args?: Record<string, unknown> };
  const Default = (stories_persona as { Default?: { args?: Record<string, unknown> } }).Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "ai-persona--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "ai-persona--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── PromptInputEffort (packages/ai/src/prompt-input-effort.tsx) ────────────────────────────────────────
import * as stories_prompt_input_effort from "../../../packages/ai/src/prompt-input-effort.stories";
describe("PromptInputEffort contract (browser)", () => {
  const meta = stories_prompt_input_effort.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_prompt_input_effort as { Default?: { args?: Record<string, unknown> } })
    .Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "ai-composer-promptinputeffort--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "ai-composer-promptinputeffort--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── PromptInputMode (packages/ai/src/prompt-input-mode.tsx) ────────────────────────────────────────
import * as stories_prompt_input_mode from "../../../packages/ai/src/prompt-input-mode.stories";
describe("PromptInputMode contract (browser)", () => {
  const meta = stories_prompt_input_mode.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_prompt_input_mode as { Default?: { args?: Record<string, unknown> } })
    .Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "ai-composer-promptinputmode--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "ai-composer-promptinputmode--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});
