// GENERATED by scripts/gen-contract-tests.mjs — do not edit; re-run the generator instead.
/**
 * Browser contract probes (axe + horizontal-overflow) for every flow
 * component with a `Default` story, swept over every built-in theme and the
 * phone/tablet/desktop widths. See scripts/gen-contract-tests.mjs.
 */
import { describe, it, expect, afterEach } from "vitest";
import { page } from "@vitest/browser/context";
import { createRoot, type Root } from "react-dom/client";
import { act, type ReactNode } from "react";
import axe from "axe-core";
import { BUILT_IN_THEMES } from "@elabs-ai/components-tokens";
import knownFailuresJson from "../../../scripts/check/contract-known-failures.json";

const KNOWN_FAILURES: Record<string, string> = knownFailuresJson;
const WIDTHS = [375, 768, 1280];

function mountReact(node: ReactNode) {
  const container = document.createElement("div");
  document.body.appendChild(container);
  const root: Root = createRoot(container);
  act(() => {
    root.render(node);
  });
  return {
    container,
    unmount() {
      act(() => {
        root.unmount();
      });
      container.remove();
    },
  };
}

afterEach(() => {
  document.documentElement.removeAttribute("data-theme");
});

/** Wrap a known, tracked failure in `it.fails` so fixing it forces the key's removal. */
function contractIt(
  storyId: string,
  theme: string,
  width: number,
  assertion: string,
  name: string,
  fn: () => void | Promise<void>,
) {
  const key = `${storyId}|${theme}|${width}|${assertion}`;
  const reason = KNOWN_FAILURES[key];
  if (reason) return it.fails(`${name} (known failure: ${reason})`, fn);
  return it(name, fn);
}

// ── InspectorPanel (packages/flow/src/inspector-panel/inspector-panel.tsx) ────────────────────────────────────────
import * as stories_inspector_panel from "../../../packages/flow/src/inspector-panel/inspector-panel.stories";
describe("InspectorPanel contract (browser)", () => {
  const meta = stories_inspector_panel.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_inspector_panel as { Default?: { args?: Record<string, unknown> } })
    .Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "flow-inspectorpanel--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "flow-inspectorpanel--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── Legend (packages/flow/src/legend/legend.tsx) ────────────────────────────────────────
import * as stories_legend from "../../../packages/flow/src/legend/legend.stories";
describe("Legend contract (browser)", () => {
  const meta = stories_legend.default as { component?: unknown; args?: Record<string, unknown> };
  const Default = (stories_legend as { Default?: { args?: Record<string, unknown> } }).Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "flow-legend--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "flow-legend--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});
