// GENERATED by scripts/gen-contract-tests.mjs — do not edit; re-run the generator instead.
/**
 * Browser contract probes (axe + horizontal-overflow) for every marketing
 * component with a `Default` story, swept over every built-in theme and the
 * phone/tablet/desktop widths. See scripts/gen-contract-tests.mjs.
 */
import { describe, it, expect, afterEach } from "vitest";
import { page } from "@vitest/browser/context";
import { createRoot, type Root } from "react-dom/client";
import { act, type ReactNode } from "react";
import axe from "axe-core";
import { BUILT_IN_THEMES } from "@elabs-ai/components-tokens";
import knownFailuresJson from "../../../scripts/check/contract-known-failures.json";

const KNOWN_FAILURES: Record<string, string> = knownFailuresJson;
const WIDTHS = [375, 768, 1280];

function mountReact(node: ReactNode) {
  const container = document.createElement("div");
  document.body.appendChild(container);
  const root: Root = createRoot(container);
  act(() => {
    root.render(node);
  });
  return {
    container,
    unmount() {
      act(() => {
        root.unmount();
      });
      container.remove();
    },
  };
}

afterEach(() => {
  document.documentElement.removeAttribute("data-theme");
});

/** Wrap a known, tracked failure in `it.fails` so fixing it forces the key's removal. */
function contractIt(
  storyId: string,
  theme: string,
  width: number,
  assertion: string,
  name: string,
  fn: () => void | Promise<void>,
) {
  const key = `${storyId}|${theme}|${width}|${assertion}`;
  const reason = KNOWN_FAILURES[key];
  if (reason) return it.fails(`${name} (known failure: ${reason})`, fn);
  return it(name, fn);
}

// ── CTASection (packages/marketing/src/cta-section/cta-section.tsx) ────────────────────────────────────────
import * as stories_cta_section from "../../../packages/marketing/src/cta-section/cta-section.stories";
describe("CTASection contract (browser)", () => {
  const meta = stories_cta_section.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_cta_section as { Default?: { args?: Record<string, unknown> } }).Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "marketing-ctasection--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "marketing-ctasection--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── FeatureGrid (packages/marketing/src/feature-grid/feature-grid.tsx) ────────────────────────────────────────
import * as stories_feature_grid from "../../../packages/marketing/src/feature-grid/feature-grid.stories";
describe("FeatureGrid contract (browser)", () => {
  const meta = stories_feature_grid.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_feature_grid as { Default?: { args?: Record<string, unknown> } })
    .Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "marketing-featuregrid--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "marketing-featuregrid--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── GatesBand (packages/marketing/src/gates-band/gates-band.tsx) ────────────────────────────────────────
import * as stories_gates_band from "../../../packages/marketing/src/gates-band/gates-band.stories";
describe("GatesBand contract (browser)", () => {
  const meta = stories_gates_band.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_gates_band as { Default?: { args?: Record<string, unknown> } }).Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "marketing-gatesband--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "marketing-gatesband--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── LogoStrip (packages/marketing/src/logo-strip/logo-strip.tsx) ────────────────────────────────────────
import * as stories_logo_strip from "../../../packages/marketing/src/logo-strip/logo-strip.stories";
describe("LogoStrip contract (browser)", () => {
  const meta = stories_logo_strip.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_logo_strip as { Default?: { args?: Record<string, unknown> } }).Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "marketing-logostrip--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "marketing-logostrip--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── StatsBand (packages/marketing/src/stats-band/stats-band.tsx) ────────────────────────────────────────
import * as stories_stats_band from "../../../packages/marketing/src/stats-band/stats-band.stories";
describe("StatsBand contract (browser)", () => {
  const meta = stories_stats_band.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_stats_band as { Default?: { args?: Record<string, unknown> } }).Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "marketing-statsband--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "marketing-statsband--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── TrustStrip (packages/marketing/src/trust-strip/trust-strip.tsx) ────────────────────────────────────────
import * as stories_trust_strip from "../../../packages/marketing/src/trust-strip/trust-strip.stories";
describe("TrustStrip contract (browser)", () => {
  const meta = stories_trust_strip.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_trust_strip as { Default?: { args?: Record<string, unknown> } }).Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "marketing-truststrip--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "marketing-truststrip--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── UseCaseCard (packages/marketing/src/use-case-card/use-case-card.tsx) ────────────────────────────────────────
import * as stories_use_case_card from "../../../packages/marketing/src/use-case-card/use-case-card.stories";
describe("UseCaseCard contract (browser)", () => {
  const meta = stories_use_case_card.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_use_case_card as { Default?: { args?: Record<string, unknown> } })
    .Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "marketing-usecasecard--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "marketing-usecasecard--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});
