// GENERATED by scripts/gen-contract-tests.mjs — do not edit; re-run the generator instead.
/**
 * Browser contract probes (axe + horizontal-overflow) for every ui
 * component with a `Default` story, swept over every built-in theme and the
 * phone/tablet/desktop widths. See scripts/gen-contract-tests.mjs.
 */
import { describe, it, expect, afterEach } from "vitest";
import { page } from "@vitest/browser/context";
import { createRoot, type Root } from "react-dom/client";
import { act, type ReactNode } from "react";
import axe from "axe-core";
import { BUILT_IN_THEMES } from "@elabs-ai/components-tokens";
import knownFailuresJson from "../../../scripts/check/contract-known-failures.json";

const KNOWN_FAILURES: Record<string, string> = knownFailuresJson;
const WIDTHS = [375, 768, 1280];

function mountReact(node: ReactNode) {
  const container = document.createElement("div");
  document.body.appendChild(container);
  const root: Root = createRoot(container);
  act(() => {
    root.render(node);
  });
  return {
    container,
    unmount() {
      act(() => {
        root.unmount();
      });
      container.remove();
    },
  };
}

afterEach(() => {
  document.documentElement.removeAttribute("data-theme");
});

/** Wrap a known, tracked failure in `it.fails` so fixing it forces the key's removal. */
function contractIt(
  storyId: string,
  theme: string,
  width: number,
  assertion: string,
  name: string,
  fn: () => void | Promise<void>,
) {
  const key = `${storyId}|${theme}|${width}|${assertion}`;
  const reason = KNOWN_FAILURES[key];
  if (reason) return it.fails(`${name} (known failure: ${reason})`, fn);
  return it(name, fn);
}

// ── AmbientField (packages/ui/src/components/ambient-field/ambient-field.tsx) ────────────────────────────────────────
import * as stories_ambient_field from "../../../packages/ui/src/components/ambient-field/ambient-field.stories";
describe("AmbientField contract (browser)", () => {
  const meta = stories_ambient_field.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_ambient_field as { Default?: { args?: Record<string, unknown> } })
    .Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "display-ambientfield--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "display-ambientfield--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── AttributionPanel (packages/ui/src/components/attribution-panel/attribution-panel.tsx) ────────────────────────────────────────
import * as stories_attribution_panel from "../../../packages/ui/src/components/attribution-panel/attribution-panel.stories";
describe("AttributionPanel contract (browser)", () => {
  const meta = stories_attribution_panel.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_attribution_panel as { Default?: { args?: Record<string, unknown> } })
    .Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "core-attributionpanel--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "core-attributionpanel--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── Badge (packages/ui/src/components/badge/badge.tsx) ────────────────────────────────────────
import * as stories_badge from "../../../packages/ui/src/components/badge/badge.stories";
describe("Badge contract (browser)", () => {
  const meta = stories_badge.default as { component?: unknown; args?: Record<string, unknown> };
  const Default = (stories_badge as { Default?: { args?: Record<string, unknown> } }).Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "core-badge--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "core-badge--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── BoundedNumber (packages/ui/src/components/bounded-number/bounded-number.tsx) ────────────────────────────────────────
import * as stories_bounded_number from "../../../packages/ui/src/components/bounded-number/bounded-number.stories";
describe("BoundedNumber contract (browser)", () => {
  const meta = stories_bounded_number.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_bounded_number as { Default?: { args?: Record<string, unknown> } })
    .Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "forms-boundednumber--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "forms-boundednumber--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── Button (packages/ui/src/components/button/button.tsx) ────────────────────────────────────────
import * as stories_button from "../../../packages/ui/src/components/button/button.stories";
describe("Button contract (browser)", () => {
  const meta = stories_button.default as { component?: unknown; args?: Record<string, unknown> };
  const Default = (stories_button as { Default?: { args?: Record<string, unknown> } }).Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "core-button--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "core-button--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── ColorPicker (packages/ui/src/components/color-picker/color-picker.tsx) ────────────────────────────────────────
import * as stories_color_picker from "../../../packages/ui/src/components/color-picker/color-picker.stories";
describe("ColorPicker contract (browser)", () => {
  const meta = stories_color_picker.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_color_picker as { Default?: { args?: Record<string, unknown> } })
    .Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "forms-colorpicker--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "forms-colorpicker--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── Combobox (packages/ui/src/components/combobox/combobox.tsx) ────────────────────────────────────────
import * as stories_combobox from "../../../packages/ui/src/components/combobox/combobox.stories";
describe("Combobox contract (browser)", () => {
  const meta = stories_combobox.default as { component?: unknown; args?: Record<string, unknown> };
  const Default = (stories_combobox as { Default?: { args?: Record<string, unknown> } }).Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "forms-combobox--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "forms-combobox--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── CommandChip (packages/ui/src/components/command-chip/command-chip.tsx) ────────────────────────────────────────
import * as stories_command_chip from "../../../packages/ui/src/components/command-chip/command-chip.stories";
describe("CommandChip contract (browser)", () => {
  const meta = stories_command_chip.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_command_chip as { Default?: { args?: Record<string, unknown> } })
    .Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "display-commandchip--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "display-commandchip--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── CommandTrigger (packages/ui/src/components/command-trigger/command-trigger.tsx) ────────────────────────────────────────
import * as stories_command_trigger from "../../../packages/ui/src/components/command-trigger/command-trigger.stories";
describe("CommandTrigger contract (browser)", () => {
  const meta = stories_command_trigger.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_command_trigger as { Default?: { args?: Record<string, unknown> } })
    .Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "navigation-commandtrigger--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "navigation-commandtrigger--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── CopyableValue (packages/ui/src/components/copyable-value/copyable-value.tsx) ────────────────────────────────────────
import * as stories_copyable_value from "../../../packages/ui/src/components/copyable-value/copyable-value.stories";
describe("CopyableValue contract (browser)", () => {
  const meta = stories_copyable_value.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_copyable_value as { Default?: { args?: Record<string, unknown> } })
    .Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "display-copyablevalue--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "display-copyablevalue--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── DatePicker (packages/ui/src/components/date-picker/date-picker.tsx) ────────────────────────────────────────
import * as stories_date_picker from "../../../packages/ui/src/components/date-picker/date-picker.stories";
describe("DatePicker contract (browser)", () => {
  const meta = stories_date_picker.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_date_picker as { Default?: { args?: Record<string, unknown> } }).Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "forms-datepicker--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "forms-datepicker--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── DateRangePicker (packages/ui/src/components/date-range-picker/date-range-picker.tsx) ────────────────────────────────────────
import * as stories_date_range_picker from "../../../packages/ui/src/components/date-range-picker/date-range-picker.stories";
describe("DateRangePicker contract (browser)", () => {
  const meta = stories_date_range_picker.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_date_range_picker as { Default?: { args?: Record<string, unknown> } })
    .Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "forms-daterangepicker--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "forms-daterangepicker--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── EmptyState (packages/ui/src/components/empty-state/empty-state.tsx) ────────────────────────────────────────
import * as stories_empty_state from "../../../packages/ui/src/components/empty-state/empty-state.stories";
describe("EmptyState contract (browser)", () => {
  const meta = stories_empty_state.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_empty_state as { Default?: { args?: Record<string, unknown> } }).Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "states-emptystate--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "states-emptystate--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── ErrorState (packages/ui/src/components/error-state/error-state.tsx) ────────────────────────────────────────
import * as stories_error_state from "../../../packages/ui/src/components/error-state/error-state.stories";
describe("ErrorState contract (browser)", () => {
  const meta = stories_error_state.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_error_state as { Default?: { args?: Record<string, unknown> } }).Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "states-errorstate--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "states-errorstate--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── IconButton (packages/ui/src/components/icon-button/icon-button.tsx) ────────────────────────────────────────
import * as stories_icon_button from "../../../packages/ui/src/components/icon-button/icon-button.stories";
describe("IconButton contract (browser)", () => {
  const meta = stories_icon_button.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_icon_button as { Default?: { args?: Record<string, unknown> } }).Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "core-iconbutton--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "core-iconbutton--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── Input (packages/ui/src/components/input/input.tsx) ────────────────────────────────────────
import * as stories_input from "../../../packages/ui/src/components/input/input.stories";
describe("Input contract (browser)", () => {
  const meta = stories_input.default as { component?: unknown; args?: Record<string, unknown> };
  const Default = (stories_input as { Default?: { args?: Record<string, unknown> } }).Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "core-input--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "core-input--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── InstallTabs (packages/ui/src/components/install-tabs/install-tabs.tsx) ────────────────────────────────────────
import * as stories_install_tabs from "../../../packages/ui/src/components/install-tabs/install-tabs.stories";
describe("InstallTabs contract (browser)", () => {
  const meta = stories_install_tabs.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_install_tabs as { Default?: { args?: Record<string, unknown> } })
    .Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "display-installtabs--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "display-installtabs--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── IntegrationMatrix (packages/ui/src/components/integration-matrix/integration-matrix.tsx) ────────────────────────────────────────
import * as stories_integration_matrix from "../../../packages/ui/src/components/integration-matrix/integration-matrix.stories";
describe("IntegrationMatrix contract (browser)", () => {
  const meta = stories_integration_matrix.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_integration_matrix as { Default?: { args?: Record<string, unknown> } })
    .Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "display-integrationmatrix--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "display-integrationmatrix--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── KeyValueEditor (packages/ui/src/components/key-value-editor/key-value-editor.tsx) ────────────────────────────────────────
import * as stories_key_value_editor from "../../../packages/ui/src/components/key-value-editor/key-value-editor.stories";
describe("KeyValueEditor contract (browser)", () => {
  const meta = stories_key_value_editor.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_key_value_editor as { Default?: { args?: Record<string, unknown> } })
    .Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "forms-keyvalueeditor--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "forms-keyvalueeditor--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── ListEditor (packages/ui/src/components/list-editor/list-editor.tsx) ────────────────────────────────────────
import * as stories_list_editor from "../../../packages/ui/src/components/list-editor/list-editor.stories";
describe("ListEditor contract (browser)", () => {
  const meta = stories_list_editor.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_list_editor as { Default?: { args?: Record<string, unknown> } }).Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "forms-listeditor--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "forms-listeditor--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── LoadingState (packages/ui/src/components/loading-state/loading-state.tsx) ────────────────────────────────────────
import * as stories_loading_state from "../../../packages/ui/src/components/loading-state/loading-state.stories";
describe("LoadingState contract (browser)", () => {
  const meta = stories_loading_state.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_loading_state as { Default?: { args?: Record<string, unknown> } })
    .Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "states-loadingstate--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "states-loadingstate--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── Meter (packages/ui/src/components/meter/meter.tsx) ────────────────────────────────────────
import * as stories_meter from "../../../packages/ui/src/components/meter/meter.stories";
describe("Meter contract (browser)", () => {
  const meta = stories_meter.default as { component?: unknown; args?: Record<string, unknown> };
  const Default = (stories_meter as { Default?: { args?: Record<string, unknown> } }).Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "display-meter--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "display-meter--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── MetricCard (packages/ui/src/components/metric-card/metric-card.tsx) ────────────────────────────────────────
import * as stories_metric_card from "../../../packages/ui/src/components/metric-card/metric-card.stories";
describe("MetricCard contract (browser)", () => {
  const meta = stories_metric_card.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_metric_card as { Default?: { args?: Record<string, unknown> } }).Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "core-metriccard--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "core-metriccard--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── ModelPicker (packages/ui/src/components/model-picker/model-picker.tsx) ────────────────────────────────────────
import * as stories_model_picker from "../../../packages/ui/src/components/model-picker/model-picker.stories";
describe("ModelPicker contract (browser)", () => {
  const meta = stories_model_picker.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_model_picker as { Default?: { args?: Record<string, unknown> } })
    .Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "core-modelpicker--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "core-modelpicker--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── NavNotifications (packages/ui/src/components/nav-notifications/nav-notifications.tsx) ────────────────────────────────────────
import * as stories_nav_notifications from "../../../packages/ui/src/components/nav-notifications/nav-notifications.stories";
describe("NavNotifications contract (browser)", () => {
  const meta = stories_nav_notifications.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_nav_notifications as { Default?: { args?: Record<string, unknown> } })
    .Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "navigation-navnotifications--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "navigation-navnotifications--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── NumberInput (packages/ui/src/components/number-input/number-input.tsx) ────────────────────────────────────────
import * as stories_number_input from "../../../packages/ui/src/components/number-input/number-input.stories";
describe("NumberInput contract (browser)", () => {
  const meta = stories_number_input.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_number_input as { Default?: { args?: Record<string, unknown> } })
    .Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "forms-numberinput--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "forms-numberinput--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── ParallaxPlane (packages/ui/src/components/parallax-plane/parallax-plane.tsx) ────────────────────────────────────────
import * as stories_parallax_plane from "../../../packages/ui/src/components/parallax-plane/parallax-plane.stories";
describe("ParallaxPlane contract (browser)", () => {
  const meta = stories_parallax_plane.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_parallax_plane as { Default?: { args?: Record<string, unknown> } })
    .Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "ground-plane--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "ground-plane--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── Rating (packages/ui/src/components/rating/rating.tsx) ────────────────────────────────────────
import * as stories_rating from "../../../packages/ui/src/components/rating/rating.stories";
describe("Rating contract (browser)", () => {
  const meta = stories_rating.default as { component?: unknown; args?: Record<string, unknown> };
  const Default = (stories_rating as { Default?: { args?: Record<string, unknown> } }).Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "forms-rating--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "forms-rating--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── RevealOnEnter (packages/ui/src/components/reveal-on-enter/reveal-on-enter.tsx) ────────────────────────────────────────
import * as stories_reveal_on_enter from "../../../packages/ui/src/components/reveal-on-enter/reveal-on-enter.stories";
describe("RevealOnEnter contract (browser)", () => {
  const meta = stories_reveal_on_enter.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_reveal_on_enter as { Default?: { args?: Record<string, unknown> } })
    .Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt("once--default", theme, width, "axe", "has no axe violations", async () => {
          const { container, unmount } = await mount();
          try {
            const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
            expect(results.violations.map((v) => v.id)).toEqual([]);
          } finally {
            unmount();
          }
        });

        contractIt(
          "once--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── SchemaForm (packages/ui/src/components/schema-form/schema-form.tsx) ────────────────────────────────────────
import * as stories_schema_form from "../../../packages/ui/src/components/schema-form/schema-form.stories";
describe("SchemaForm contract (browser)", () => {
  const meta = stories_schema_form.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_schema_form as { Default?: { args?: Record<string, unknown> } }).Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "forms-schemaform--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "forms-schemaform--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── SectionHeader (packages/ui/src/components/section-header/section-header.tsx) ────────────────────────────────────────
import * as stories_section_header from "../../../packages/ui/src/components/section-header/section-header.stories";
describe("SectionHeader contract (browser)", () => {
  const meta = stories_section_header.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_section_header as { Default?: { args?: Record<string, unknown> } })
    .Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "layout-sectionheader--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "layout-sectionheader--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── SegmentedField (packages/ui/src/components/segmented-field/segmented-field.tsx) ────────────────────────────────────────
import * as stories_segmented_field from "../../../packages/ui/src/components/segmented-field/segmented-field.stories";
describe("SegmentedField contract (browser)", () => {
  const meta = stories_segmented_field.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_segmented_field as { Default?: { args?: Record<string, unknown> } })
    .Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "forms-segmentedfield--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "forms-segmentedfield--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── SliderNumber (packages/ui/src/components/slider-number/slider-number.tsx) ────────────────────────────────────────
import * as stories_slider_number from "../../../packages/ui/src/components/slider-number/slider-number.stories";
describe("SliderNumber contract (browser)", () => {
  const meta = stories_slider_number.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_slider_number as { Default?: { args?: Record<string, unknown> } })
    .Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "forms-slidernumber--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "forms-slidernumber--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── SpecPlayground (packages/ui/src/components/spec-playground/spec-playground.tsx) ────────────────────────────────────────
import * as stories_spec_playground from "../../../packages/ui/src/components/spec-playground/spec-playground.stories";
describe("SpecPlayground contract (browser)", () => {
  const meta = stories_spec_playground.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_spec_playground as { Default?: { args?: Record<string, unknown> } })
    .Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "launch-checklist--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "launch-checklist--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── StatusBadge (packages/ui/src/components/status-badge/status-badge.tsx) ────────────────────────────────────────
import * as stories_status_badge from "../../../packages/ui/src/components/status-badge/status-badge.stories";
describe("StatusBadge contract (browser)", () => {
  const meta = stories_status_badge.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_status_badge as { Default?: { args?: Record<string, unknown> } })
    .Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "core-statusbadge--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "core-statusbadge--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── SurfaceTour (packages/ui/src/components/surface-tour/surface-tour.tsx) ────────────────────────────────────────
import * as stories_surface_tour from "../../../packages/ui/src/components/surface-tour/surface-tour.stories";
describe("SurfaceTour contract (browser)", () => {
  const meta = stories_surface_tour.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_surface_tour as { Default?: { args?: Record<string, unknown> } })
    .Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "layout-surfacetour--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "layout-surfacetour--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── TagInput (packages/ui/src/components/tag-input/tag-input.tsx) ────────────────────────────────────────
import * as stories_tag_input from "../../../packages/ui/src/components/tag-input/tag-input.stories";
describe("TagInput contract (browser)", () => {
  const meta = stories_tag_input.default as { component?: unknown; args?: Record<string, unknown> };
  const Default = (stories_tag_input as { Default?: { args?: Record<string, unknown> } }).Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "forms-taginput--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "forms-taginput--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── Text (packages/ui/src/components/typography/typography.tsx) ────────────────────────────────────────
import * as stories_text from "../../../packages/ui/src/components/typography/typography.stories";
describe("Text contract (browser)", () => {
  const meta = stories_text.default as { component?: unknown; args?: Record<string, unknown> };
  const Default = (stories_text as { Default?: { args?: Record<string, unknown> } }).Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "foundations-typography--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "foundations-typography--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── Textarea (packages/ui/src/components/textarea/textarea.tsx) ────────────────────────────────────────
import * as stories_textarea from "../../../packages/ui/src/components/textarea/textarea.stories";
describe("Textarea contract (browser)", () => {
  const meta = stories_textarea.default as { component?: unknown; args?: Record<string, unknown> };
  const Default = (stories_textarea as { Default?: { args?: Record<string, unknown> } }).Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "core-textarea--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "core-textarea--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── ThemeFamilySwitch (packages/ui/src/components/theme-family-switch/theme-family-switch.tsx) ────────────────────────────────────────
import * as stories_theme_family_switch from "../../../packages/ui/src/components/theme-family-switch/theme-family-switch.stories";
describe("ThemeFamilySwitch contract (browser)", () => {
  const meta = stories_theme_family_switch.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_theme_family_switch as { Default?: { args?: Record<string, unknown> } })
    .Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "core-themefamilyswitch--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "core-themefamilyswitch--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── Timeline (packages/ui/src/components/timeline/timeline.tsx) ────────────────────────────────────────
import * as stories_timeline from "../../../packages/ui/src/components/timeline/timeline.stories";
describe("Timeline contract (browser)", () => {
  const meta = stories_timeline.default as { component?: unknown; args?: Record<string, unknown> };
  const Default = (stories_timeline as { Default?: { args?: Record<string, unknown> } }).Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "core-timeline--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "core-timeline--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── Toggle (packages/ui/src/components/toggle/toggle.tsx) ────────────────────────────────────────
import * as stories_toggle from "../../../packages/ui/src/components/toggle/toggle.stories";
describe("Toggle contract (browser)", () => {
  const meta = stories_toggle.default as { component?: unknown; args?: Record<string, unknown> };
  const Default = (stories_toggle as { Default?: { args?: Record<string, unknown> } }).Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "forms-toggle--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "forms-toggle--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── Transfer (packages/ui/src/components/transfer/transfer.tsx) ────────────────────────────────────────
import * as stories_transfer from "../../../packages/ui/src/components/transfer/transfer.stories";
describe("Transfer contract (browser)", () => {
  const meta = stories_transfer.default as { component?: unknown; args?: Record<string, unknown> };
  const Default = (stories_transfer as { Default?: { args?: Record<string, unknown> } }).Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "forms-transfer--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "forms-transfer--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── Tree (packages/ui/src/components/tree/tree.tsx) ────────────────────────────────────────
import * as stories_tree from "../../../packages/ui/src/components/tree/tree.stories";
describe("Tree contract (browser)", () => {
  const meta = stories_tree.default as { component?: unknown; args?: Record<string, unknown> };
  const Default = (stories_tree as { Default?: { args?: Record<string, unknown> } }).Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "navigation-tree--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "navigation-tree--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── TreeSelect (packages/ui/src/components/tree-select/tree-select.tsx) ────────────────────────────────────────
import * as stories_tree_select from "../../../packages/ui/src/components/tree-select/tree-select.stories";
describe("TreeSelect contract (browser)", () => {
  const meta = stories_tree_select.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_tree_select as { Default?: { args?: Record<string, unknown> } }).Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "forms-treeselect--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "forms-treeselect--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── VirtualSelect (packages/ui/src/components/virtual-select/virtual-select.tsx) ────────────────────────────────────────
import * as stories_virtual_select from "../../../packages/ui/src/components/virtual-select/virtual-select.stories";
describe("VirtualSelect contract (browser)", () => {
  const meta = stories_virtual_select.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_virtual_select as { Default?: { args?: Record<string, unknown> } })
    .Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "forms-virtualselect--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "forms-virtualselect--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});

// ── WorkspacePicker (packages/ui/src/components/workspace-picker/workspace-picker.tsx) ────────────────────────────────────────
import * as stories_workspace_picker from "../../../packages/ui/src/components/workspace-picker/workspace-picker.stories";
describe("WorkspacePicker contract (browser)", () => {
  const meta = stories_workspace_picker.default as {
    component?: unknown;
    args?: Record<string, unknown>;
  };
  const Default = (stories_workspace_picker as { Default?: { args?: Record<string, unknown> } })
    .Default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see file header
  const Component = meta.component as any;
  const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };

  for (const theme of BUILT_IN_THEMES) {
    for (const width of WIDTHS) {
      describe(`theme=${theme} width=${width}`, () => {
        async function mount() {
          document.documentElement.setAttribute("data-theme", theme);
          await page.viewport(width, 900);
          return mountReact(<Component {...args} />);
        }

        contractIt(
          "core-workspacepicker--default",
          theme,
          width,
          "axe",
          "has no axe violations",
          async () => {
            const { container, unmount } = await mount();
            try {
              const results = await axe.run(container, { runOnly: ["wcag2a", "wcag2aa"] });
              expect(results.violations.map((v) => v.id)).toEqual([]);
            } finally {
              unmount();
            }
          },
        );

        contractIt(
          "core-workspacepicker--default",
          theme,
          width,
          "overflow",
          "does not overflow horizontally",
          async () => {
            const { unmount } = await mount();
            try {
              expect(document.documentElement.scrollWidth).toBeLessThanOrEqual(window.innerWidth);
            } finally {
              unmount();
            }
          },
        );
      });
    }
  }
});
