// Selection gesture engine (ADR 0040, RM-136 contract + RM-142 engine).
export * from "./types";
export {
  CLICK_SENSITIVITY,
  createGestureState,
  gestureReducer,
  isGestureActive,
  NO_MODIFIERS,
  resolveMode,
  type GestureEngineMode,
  type GestureEvent,
  type GestureModifiers,
  type GesturePhase,
  type GesturePoint,
  type GestureRegion,
  type GestureState,
} from "./gesture-machine";
export {
  bandCategoriesInRange,
  bandCategoryAt,
  LASSO_SIMPLIFY_EPSILON,
  LASSO_SNAP_DISTANCE,
  normalizeRect,
  pathToSvgD,
  pixelRangeToData,
  pixelToData,
  RADIAL_SEGMENTS,
  radialToPolygon,
  simplifyPath,
  snapToClose,
  type BandScaleLike,
  type GestureAxis,
  type LinearScaleLike,
  type PixelRect,
  type TimeScaleLike,
} from "./geometry";
export {
  hitsInBand,
  hitsInPolygon,
  hitsInRect,
  pointInPolygon,
  pointInRect,
  shapeBounds,
  shapeCenter,
  shapeHitsPolygon,
  shapeHitsRect,
  visibleOnly,
  type ChartMarkGeometry,
  type ChartMarkShape,
  type HitBandOptions,
  type HitRectOptions,
} from "./hit-test";
export {
  CLICK_HIT_RADIUS,
  distinctCategories,
  gestureGeometry,
  hitAtPoint,
  lassoPolygon,
  resolveGestureHits,
  resolveSelectionIntent,
  toChartDatapoint,
  type ResolveIntentOptions,
} from "./resolve-intent";
export {
  ChartMarkGeometryProvider,
  createMarkGeometryStore,
  useMarkGeometry,
  useMarkGeometryStore,
  useRegisterMarkGeometry,
  type ChartMarkGeometryProviderProps,
  type MarkGeometryStore,
} from "./mark-registry";
export {
  accumulateProvisional,
  gestureOverlayGeometry,
  initialGestureMode,
  LONG_PRESS_MS,
  useChartGesture,
  type GestureOverlayGeometry,
  type GesturePointerEvent,
  type GesturePointerHandlers,
  type UseChartGestureOptions,
  type UseChartGestureResult,
} from "./use-chart-gesture";
export {
  GESTURE_FILL_OPACITY,
  GESTURE_HALO_WIDTH,
  GESTURE_OUTLINE_WIDTH,
  GestureOverlay,
  type GestureOverlayProps,
} from "./gesture-overlay";
export {
  ChartSelectionGestureLayer,
  ChartSelectionGestureScope,
  isSelectionGestureEnabled,
  useChartGestureOverlay,
  useChartSelectionGestureScope,
  type ChartSelectionGestureLayerProps,
  type ChartSelectionGestureScopeProps,
} from "./chart-gesture-layer";
