// GENERATED by packages/cli/scripts/gen-a2ui-catalog.mjs from
// packages/ai/src/a2ui/catalog.source.json + brand-ui.manifest.json — do not edit;
// edit the source file (or the component) and run `pnpm gen`.
import type { A2uiCatalogSchema } from "./spec";

export const A2UI_CATALOG_VERSION = "1";

export const A2UI_CATALOG_SCHEMA: A2uiCatalogSchema = {
  Accordion: {
    children: true,
    props: {
      collapsible: {
        type: "boolean",
      },
      defaultValue: {
        type: "string",
      },
      type: {
        enum: ["single", "multiple"],
        required: true,
        type: "string",
      },
    },
    events: {
      change: "onValueChange",
    },
    source: "@elabs-ai/components-ui",
  },
  AccordionContent: {
    children: true,
    props: {},
    events: {},
    source: "@elabs-ai/components-ui",
  },
  AccordionItem: {
    children: true,
    props: {
      value: {
        type: "string",
        required: true,
      },
    },
    events: {},
    source: "@elabs-ai/components-ui",
  },
  AccordionTrigger: {
    children: true,
    props: {},
    events: {},
    source: "@elabs-ai/components-ui",
  },
  Alert: {
    children: true,
    props: {
      variant: {
        enum: ["default", "destructive", "success", "warning", "info"],
        type: "string",
      },
    },
    events: {},
    source: "@elabs-ai/components-ui",
    summary: "Compose AlertTitle + AlertDescription inside.",
  },
  AlertDescription: {
    children: true,
    props: {
      measure: {
        type: "boolean",
        description:
          "Cap the line length to a readable prose measure (`max-w-prose`, ~65ch) for genuine paragraph content (#339). Off by default — short, label-style descriptions…",
      },
    },
    events: {},
    source: "@elabs-ai/components-ui",
  },
  AlertTitle: {
    children: true,
    props: {},
    events: {},
    source: "@elabs-ai/components-ui",
  },
  Avatar: {
    children: true,
    props: {},
    events: {},
    source: "@elabs-ai/components-ui",
    summary: "Compose AvatarFallback (initials) inside.",
  },
  AvatarFallback: {
    children: true,
    props: {},
    events: {},
    source: "@elabs-ai/components-ui",
  },
  Badge: {
    children: true,
    props: {
      variant: {
        type: "string",
        enum: ["default", "secondary", "outline", "success", "warning", "destructive", "info"],
        default: "default",
      },
    },
    events: {},
    source: "@elabs-ai/components-ui",
    summary: "Compact status/label chip (status, count, category).",
  },
  BentoGrid: {
    children: true,
    props: {
      spotlight: {
        type: "boolean",
        description:
          "Enable the cursor-following spotlight on every tile in this grid. Individual tiles can still opt out (or in) with their own `spotlight` prop. Disabled entire…",
      },
    },
    events: {},
    source: "@elabs-ai/components-ui",
    summary: "Feature/bento grid; children are BentoGridItem.",
  },
  BentoGridItem: {
    children: true,
    props: {
      size: {
        type: "string",
        description:
          'Size preset. Resolves to a col + row span. Overridden by explicit `span`. @default "sm"',
        enum: ["sm", "md", "lg", "hero"],
      },
      span: {
        type: "object",
        description:
          "Explicit grid span. Wins over `size`. Spans clamp gracefully on narrow layouts — a `col: 4` on a 2-col grid becomes `span min(4, 2)`.",
      },
      spotlight: {
        type: "boolean",
        description:
          "Enable the cursor-following spotlight gradient on this tile. Omit to inherit the parent `BentoGrid`'s `spotlight` (itself `false` by default) — so the effect…",
      },
    },
    events: {},
    source: "@elabs-ai/components-ui",
  },
  Button: {
    children: true,
    props: {
      disabled: {
        type: "boolean",
      },
      size: {
        type: "string",
        enum: ["sm", "default", "lg", "icon", "icon-sm", "icon-lg"],
        default: "default",
      },
      type: {
        enum: ["button", "submit"],
        default: "button",
        type: "string",
      },
      variant: {
        type: "string",
        enum: ["default", "secondary", "destructive", "outline", "outline-subtle", "ghost", "link"],
        default: "default",
      },
    },
    events: {
      click: "onClick",
    },
    source: "@elabs-ai/components-ui",
    summary: 'An action. Bind `on.click`; one `variant: "default"` per group.',
  },
  ButtonGroup: {
    children: true,
    props: {},
    events: {},
    source: "@elabs-ai/components-ui",
  },
  Card: {
    children: true,
    props: {
      detail: {
        type: "node",
        description:
          "Optional detail-panel content. **Undefined → a plain card** (today's single `<div>` — no grid, no panel, zero behaviour change).",
      },
      detailLabel: {
        type: "string",
        description: 'Accessible label for the detail region. @default "Details"',
      },
      detailPlacement: {
        type: "string",
        enum: ["side", "bottom"],
        description: 'Which edge the detail panel sits on. @default "side"',
      },
      detailReveal: {
        type: "string",
        enum: ["fixed", "hover"],
        description:
          "`fixed` (default, accessible) → panel always visible. `hover` → hidden at rest, revealed on hover **and** keyboard `focus-within` at a FIXED outer footprint …",
      },
      detailSize: {
        type: "string",
        description:
          'Detail track size (any CSS length). @default "16rem" (side) / "auto" (bottom)',
      },
      interactive: {
        type: "string",
        enum: ["true", "false"],
        default: "false",
      },
    },
    events: {},
    source: "@elabs-ai/components-ui",
    summary: "The one generic surface — compose CardHeader / CardContent / CardFooter inside.",
  },
  CardAction: {
    children: true,
    props: {},
    events: {},
    source: "@elabs-ai/components-ui",
    summary: "The header's trailing action slot (a Button, a Badge).",
  },
  CardContent: {
    children: true,
    props: {},
    events: {},
    source: "@elabs-ai/components-ui",
  },
  CardDescription: {
    children: true,
    props: {
      measure: {
        type: "boolean",
        description:
          "Cap the line length to a readable prose measure (`max-w-prose`, ~65ch) for genuine paragraph content (#339). Off by default — short, subtitle-style descripti…",
      },
    },
    events: {},
    source: "@elabs-ai/components-ui",
  },
  CardFooter: {
    children: true,
    props: {},
    events: {},
    source: "@elabs-ai/components-ui",
  },
  CardHeader: {
    children: true,
    props: {},
    events: {},
    source: "@elabs-ai/components-ui",
  },
  CardTitle: {
    children: true,
    props: {},
    events: {},
    source: "@elabs-ai/components-ui",
  },
  Checkbox: {
    children: false,
    props: {
      "aria-label": {
        type: "string",
      },
      defaultChecked: {
        type: "boolean",
      },
      disabled: {
        type: "boolean",
      },
      id: {
        type: "string",
      },
    },
    events: {
      change: "onCheckedChange",
    },
    source: "@elabs-ai/components-ui",
    summary: "Binary on/off toggle within a form (multi-select within a group).",
  },
  Collapsible: {
    children: true,
    props: {
      defaultOpen: {
        type: "boolean",
      },
    },
    events: {
      change: "onOpenChange",
    },
    source: "@elabs-ai/components-ui",
  },
  CollapsibleContent: {
    children: true,
    props: {},
    events: {},
    source: "@elabs-ai/components-ui",
  },
  CollapsibleTrigger: {
    children: true,
    props: {
      asChild: {
        type: "boolean",
      },
    },
    events: {},
    source: "@elabs-ai/components-ui",
  },
  Descriptions: {
    children: true,
    props: {
      columns: {
        type: "number",
        enum: [1, 2, 3],
        description:
          "Number of columns at the widest breakpoint. Collapses to a single column on small screens. Default 1.",
      },
      layout: {
        type: "string",
        description:
          "`horizontal` places the label beside the value; `vertical` stacks the label above the value. Default `horizontal`.",
        enum: ["horizontal", "vertical"],
      },
    },
    events: {},
    source: "@elabs-ai/components-ui",
    summary: "Key–value list; children are DescriptionsItem.",
  },
  DescriptionsItem: {
    children: true,
    props: {
      label: {
        type: "node",
        required: true,
        description: "The term / label for this entry.",
      },
      numeric: {
        type: "boolean",
        description:
          "When the value is numeric, set this so the value uses `tabular-nums` for aligned digits.",
      },
    },
    events: {},
    source: "@elabs-ai/components-ui",
  },
  EmptyState: {
    children: false,
    props: {
      actions: {
        type: "node",
        description: "Primary/secondary actions.",
      },
      description: {
        type: "node",
      },
      icon: {
        type: "node",
        description:
          "Optional icon shown above the title, clamped to a fixed 40×40 (this wrapper only ever forwards `icon` to `StatePanel`, never `illustration` — for a larger, u…",
      },
      title: {
        type: "node",
        required: true,
      },
    },
    events: {},
    source: "@elabs-ai/components-ui",
    summary: "Nothing here yet — title, description, optional actions.",
  },
  Grid: {
    builtin: true,
    children: true,
    props: {
      columns: {
        enum: [1, 2, 3, 4],
        default: 2,
        type: "number",
      },
      gap: {
        enum: ["none", "xs", "sm", "md", "lg"],
        default: "md",
        type: "string",
      },
    },
    events: {},
    source: "builtin",
    summary: "Responsive CSS grid, 1–4 equal columns (collapses to one column on narrow screens).",
  },
  Heading: {
    children: true,
    props: {
      level: {
        type: "number",
        description: "Semantic heading level — drives the rendered tag AND the default size.",
        enum: [1, 2, 3, 4, 5, 6],
        default: 2,
      },
      size: {
        type: "string",
        enum: ["display", "title", "subtitle"],
        default: "title",
      },
    },
    events: {},
    source: "@elabs-ai/components-ui",
    summary: "Section heading; `level` sets the HTML rank (1–6), `size` the type role.",
  },
  Input: {
    children: false,
    props: {
      "aria-label": {
        type: "string",
      },
      defaultValue: {
        type: "string",
      },
      disabled: {
        type: "boolean",
      },
      id: {
        type: "string",
      },
      placeholder: {
        type: "string",
      },
      required: {
        type: "boolean",
      },
      type: {
        enum: ["text", "email", "number", "password", "search", "tel", "url", "date"],
        type: "string",
      },
    },
    events: {
      change: "onChange",
    },
    source: "@elabs-ai/components-ui",
    summary: "Single-line text field — the base form input.",
  },
  Kbd: {
    children: true,
    props: {},
    events: {},
    source: "@elabs-ai/components-ui",
  },
  Label: {
    children: true,
    props: {
      htmlFor: {
        type: "string",
      },
    },
    events: {},
    source: "@elabs-ai/components-ui",
  },
  MetricCard: {
    children: false,
    props: {
      announceLoading: {
        type: "boolean",
        description:
          "Whether this tile announces its own `loading` state via a live region. Set to `false` when several tiles are composed inside a container that already announc…",
      },
      copyExactValue: {
        type: "boolean",
        description:
          "Offer the exact figure on click when a numeric `value` was shortened. Default: `true`. Turning it off leaves a compacted number with no way back to its digit…",
      },
      currency: {
        type: "string",
        description: 'ISO 4217 code for `valueFormat: "currency"`. Default: `"USD"`.',
      },
      delta: {
        type: "string",
        description: 'Signed change, e.g. "+12.4%". Direction colors it.',
      },
      deltaDirection: {
        type: "string",
        enum: ["up", "down", "neutral"],
      },
      description: {
        type: "node",
        description: "Secondary line under the value — sublabel / context.",
      },
      evidence: {
        type: "node",
        description:
          "Optional grounding footer (research 11 §B.5 KPI-3) — connects a cited figure to its source (e.g. an `EvidenceChip` from `@elabs-ai/components-ai`). Rendered …",
      },
      icon: {
        type: "node",
      },
      label: {
        type: "node",
        required: true,
      },
      loading: {
        type: "boolean",
        description:
          "Loading vs ready — renders a layout-shaped skeleton (matching the real box height) instead of the value/label/delta text. Default: `false`.",
      },
      positiveIsGood: {
        type: "boolean",
        description: 'Whether "up" is good (green) — flip for metrics where down is good.',
      },
      sparkline: {
        type: "node",
        description:
          'Trend slot rendered directly under the value (RM-072) — pass a `<Sparkline …/>` from `@elabs-ai/components-charts`. Hidden at `size="sm"`.',
      },
      value: {
        type: "node",
        required: true,
      },
      valueFormat: {
        type: "string",
        description:
          'How to render a NUMERIC `value`. Default: `"compact"`. Ignored for every other `ReactNode` — a string you already formatted is rendered verbatim.',
        enum: ["number", "compact", "currency", "percent"],
      },
      visual: {
        type: "node",
        description: "Optional inline visual shown under the value/description.",
      },
    },
    events: {},
    source: "@elabs-ai/components-ui",
    summary: "One KPI: label, value, optional delta. Put several in a Grid.",
  },
  Progress: {
    children: false,
    props: {
      "aria-label": {
        type: "string",
      },
      marker: {
        type: "number",
        description:
          'Reference point (0–100, same scale as `value`) — e.g. an "expected by today" pace or a target — rendered as a thin vertical tick on the track. Unset (default…',
      },
      markerLabel: {
        type: "string",
        description:
          'What `marker` represents (already localized by the caller — e.g. `"expected 70% by today"`). When set, it is appended to the progress bar\'s accessible value …',
      },
      max: {
        type: "number",
      },
      value: {
        type: "number",
        required: true,
      },
      variant: {
        type: "string",
        enum: ["default", "success", "warning", "destructive"],
        default: "default",
      },
    },
    events: {},
    source: "@elabs-ai/components-ui",
  },
  RadioGroup: {
    children: true,
    props: {
      "aria-label": {
        type: "string",
      },
      defaultValue: {
        type: "string",
      },
    },
    events: {
      change: "onValueChange",
    },
    source: "@elabs-ai/components-ui",
    summary: "Mutually-exclusive single choice from a small visible set.",
  },
  RadioGroupItem: {
    children: false,
    props: {
      "aria-label": {
        type: "string",
      },
      disabled: {
        type: "boolean",
      },
      id: {
        type: "string",
      },
      value: {
        type: "string",
        required: true,
      },
    },
    events: {},
    source: "@elabs-ai/components-ui",
  },
  SectionHeader: {
    children: false,
    props: {
      actions: {
        type: "node",
        description: "Right-aligned actions (buttons, menus).",
      },
      description: {
        type: "node",
      },
      eyebrow: {
        type: "node",
        description: "Optional element rendered above the title (eyebrow / breadcrumbs).",
      },
      title: {
        type: "node",
        required: true,
      },
    },
    events: {},
    source: "@elabs-ai/components-ui",
    summary: "Title + description + optional actions above a region.",
  },
  Select: {
    children: true,
    props: {
      defaultValue: {
        type: "string",
      },
      disabled: {
        type: "boolean",
      },
    },
    events: {
      change: "onValueChange",
    },
    source: "@elabs-ai/components-ui",
    summary: "Compose SelectTrigger (SelectValue) + SelectContent (SelectItem…).",
  },
  SelectContent: {
    children: true,
    props: {},
    events: {},
    source: "@elabs-ai/components-ui",
  },
  SelectItem: {
    children: true,
    props: {
      disabled: {
        type: "boolean",
      },
      value: {
        type: "string",
        required: true,
      },
    },
    events: {},
    source: "@elabs-ai/components-ui",
  },
  SelectTrigger: {
    children: true,
    props: {
      "aria-label": {
        type: "string",
      },
      autoTitle: {
        type: "boolean",
        description:
          "Auto-set a native `title` from the trigger's rendered text — but ONLY while that text is actually clipped (default `true`). Set `false` when the trigger is a…",
      },
      size: {
        type: "string",
        enum: ["sm", "default"],
      },
    },
    events: {},
    source: "@elabs-ai/components-ui",
  },
  SelectValue: {
    children: false,
    props: {
      placeholder: {
        type: "string",
      },
    },
    events: {},
    source: "@elabs-ai/components-ui",
  },
  Separator: {
    children: false,
    props: {
      orientation: {
        enum: ["horizontal", "vertical"],
        default: "horizontal",
        type: "string",
      },
    },
    events: {},
    source: "@elabs-ai/components-ui",
  },
  Slider: {
    children: false,
    props: {
      "aria-label": {
        type: "string",
      },
      defaultValue: {
        type: "array",
      },
      max: {
        type: "number",
      },
      min: {
        type: "number",
      },
      step: {
        type: "number",
      },
      thumbProps: {
        type: "array",
        description:
          "Escape hatch spread onto the thumb LAST — for `data-*`/`style`/etc, or to deliberately override `aria-label`/`aria-labelledby`/`aria-valuetext` (an explicit …",
      },
    },
    events: {
      change: "onValueChange",
    },
    source: "@elabs-ai/components-ui",
  },
  Stack: {
    builtin: true,
    children: true,
    props: {
      align: {
        enum: ["start", "center", "end", "stretch"],
        default: "stretch",
        type: "string",
      },
      direction: {
        enum: ["column", "row"],
        default: "column",
        type: "string",
      },
      gap: {
        enum: ["none", "xs", "sm", "md", "lg"],
        default: "md",
        type: "string",
      },
      justify: {
        enum: ["start", "center", "end", "between"],
        default: "start",
        type: "string",
      },
      wrap: {
        type: "boolean",
        default: false,
      },
    },
    events: {},
    source: "builtin",
    summary:
      "Vertical or horizontal flex group. The default container — put siblings in a Stack, never bare.",
  },
  StatePanel: {
    children: false,
    props: {
      actions: {
        type: "node",
        description: "Primary / secondary action buttons.",
      },
      description: {
        type: "node",
        description: "Supporting description below the title.",
      },
      icon: {
        type: "node",
        description:
          'Icon shown above the title, clamped to a uniform 40×40 so mismatched glyphs stay tidy. For `"error"` defaults to a built-in warning triangle. For `"loading"`…',
      },
      illustration: {
        type: "node",
        description:
          "A larger illustration (one of `@elabs-ai/components-ui`'s shipped `*Illustration` components, or a consumer's own `ReactNode`) shown above the title instead …",
      },
      kind: {
        type: "string",
        enum: ["empty", "error", "loading"],
        default: "empty",
      },
      loadingLabel: {
        type: "string",
        description: 'Accessible label for the spinner in loading state. @default "Loading…"',
      },
      size: {
        type: "string",
        enum: ["sm", "md", "lg"],
        description: 'Spinner size (loading kind only). @default "md"',
      },
      title: {
        type: "node",
        description: "Heading text.",
      },
      titleAs: {
        type: "string",
        enum: ["div", "h1", "h2", "h3", "h4", "h5", "h6"],
        description:
          "Heading level for the panel's title (#328 convention). Set this to the level that correctly follows whatever heading precedes this panel in the document outl…",
      },
    },
    events: {},
    source: "@elabs-ai/components-ui",
    summary: "An empty / error / loading message panel.",
  },
  StatusBadge: {
    children: false,
    props: {
      hideIcon: {
        type: "boolean",
        description: "Render label-only (no status icon).",
      },
      size: {
        type: "string",
        enum: ["sm", "md"],
        default: "md",
      },
      status: {
        type: "string",
        required: true,
        description: "The canonical execution status, or a mapped out-of-vocabulary one (#363).",
        enum: [
          "pending",
          "running",
          "complete",
          "awaiting-approval",
          "denied",
          "failed",
          "skipped",
        ],
      },
    },
    events: {},
    source: "@elabs-ai/components-ui",
    summary: "A closed status vocabulary with icon + text (never colour alone).",
  },
  Switch: {
    children: false,
    props: {
      "aria-label": {
        type: "string",
      },
      defaultChecked: {
        type: "boolean",
      },
      disabled: {
        type: "boolean",
      },
      id: {
        type: "string",
      },
    },
    events: {
      change: "onCheckedChange",
    },
    source: "@elabs-ai/components-ui",
    summary: "Immediate on/off setting toggle (applies on change, not on submit).",
  },
  Table: {
    children: true,
    props: {},
    events: {},
    source: "@elabs-ai/components-ui",
    summary: "Compose TableHeader/TableBody → TableRow → TableHead/TableCell.",
  },
  TableBody: {
    children: true,
    props: {},
    events: {},
    source: "@elabs-ai/components-ui",
  },
  TableCaption: {
    children: true,
    props: {},
    events: {},
    source: "@elabs-ai/components-ui",
  },
  TableCell: {
    children: true,
    props: {},
    events: {},
    source: "@elabs-ai/components-ui",
  },
  TableFooter: {
    children: true,
    props: {},
    events: {},
    source: "@elabs-ai/components-ui",
  },
  TableHead: {
    children: true,
    props: {},
    events: {},
    source: "@elabs-ai/components-ui",
  },
  TableHeader: {
    children: true,
    props: {},
    events: {},
    source: "@elabs-ai/components-ui",
  },
  TableRow: {
    children: true,
    props: {},
    events: {},
    source: "@elabs-ai/components-ui",
  },
  Tabs: {
    children: true,
    props: {
      defaultValue: {
        type: "string",
        required: true,
      },
    },
    events: {
      change: "onValueChange",
    },
    source: "@elabs-ai/components-ui",
    summary: "Compose TabsList (TabsTrigger…) + TabsContent per value.",
  },
  TabsContent: {
    children: true,
    props: {
      value: {
        type: "string",
        required: true,
      },
    },
    events: {},
    source: "@elabs-ai/components-ui",
  },
  TabsList: {
    children: true,
    props: {
      variant: {
        type: "string",
        enum: ["segmented", "underline"],
        default: "segmented",
      },
    },
    events: {},
    source: "@elabs-ai/components-ui",
  },
  TabsTrigger: {
    children: true,
    props: {
      disabled: {
        type: "boolean",
      },
      value: {
        type: "string",
        required: true,
      },
    },
    events: {},
    source: "@elabs-ai/components-ui",
  },
  Text: {
    children: true,
    props: {
      tone: {
        type: "string",
        enum: ["default", "muted", "primary"],
        default: "default",
      },
      variant: {
        type: "string",
        enum: ["lead", "body", "caption", "meta", "kpi", "code"],
        default: "body",
      },
    },
    events: {},
    source: "@elabs-ai/components-ui",
    summary: "A paragraph or inline run of text with a type role and tone.",
  },
  Textarea: {
    children: false,
    props: {
      "aria-label": {
        type: "string",
      },
      defaultValue: {
        type: "string",
      },
      disabled: {
        type: "boolean",
      },
      id: {
        type: "string",
      },
      placeholder: {
        type: "string",
      },
      rows: {
        type: "number",
      },
    },
    events: {
      change: "onChange",
    },
    source: "@elabs-ai/components-ui",
  },
  Timeline: {
    children: false,
    props: {
      items: {
        type: "array",
        required: true,
        description: '[{ title, description?, status?: "done"|"active"|"pending", timestamp? }]',
      },
    },
    events: {},
    source: "@elabs-ai/components-ui",
    summary: "Ordered status timeline from `items` (title, status, timestamp, description).",
  },
};
