/**
 * manifest-compat.test.mjs — locks PR #97 Codex finding 5
 * (packages/cli/lib/core.mjs, `flat()`): a manifest generated by the release
 * before commit 05b6040 (#86) still lives in plenty of checkouts —
 * `types`/`otherExports` were bare name-string arrays back then; `bucketExports()`
 * has kept `{name, module}` objects for both buckets since that commit.
 * `loadManifest()` reads a checkout-local `brand-ui.manifest.json` verbatim off
 * disk and prioritizes it over the bundled/generated manifest, with no version
 * tag and no migration step. Against an old-shape manifest, `flat()` built
 * `type`/`export` rows straight from the bucket entries assuming the new
 * `{name, module}` shape, so every such row shipped `name: undefined` — and
 * every reader built on `flat()` (`bin/brand-ui.mjs` search/docs,
 * `lib/mcp.mjs` search/docs, `lib/engine.mjs` map) calls `.toLowerCase()` on
 * that `name` and crashes with `TypeError: Cannot read properties of
 * undefined (reading 'toLowerCase')`.
 *
 * This test fabricates an old-shape `brand-ui.manifest.json` (the exact
 * scenario a stale checkout — or a consumer's own monorepo that hasn't
 * regenerated its manifest — produces), loads it through the real
 * `loadManifest()`, and asserts `flat()` normalizes both the historical
 * string shape and the current object shape instead of crashing.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { loadManifest, flat } from "../lib/core.mjs";

/** Manifest shape written by the release BEFORE commit 05b6040 (#86) — bare
 *  name-string arrays for `types`/`otherExports`, no `module`, in both the
 *  root package buckets and a subpath's buckets. */
function oldShapeManifest() {
  return {
    name: "brand-ui",
    packages: {
      "@elabs-ai/components-ui": {
        path: "packages/ui",
        components: [{ name: "Button", module: "packages/ui/src/button/button.tsx" }],
        hooks: [],
        types: ["ButtonProps"],
        otherExports: ["createSelectionColumn"],
        subpaths: {
          "@elabs-ai/components-ui/some-subpath": {
            components: [],
            hooks: [],
            types: ["SubpathProps"],
            otherExports: ["subpathHelper"],
          },
        },
      },
    },
  };
}

/** Write `manifest` as the checkout-local `brand-ui.manifest.json` in a
 *  throwaway directory, run `body(dir)`, then clean up. */
function withFixtureManifest(manifest, body) {
  const dir = mkdtempSync(join(tmpdir(), "brand-ui-manifest-compat-"));
  writeFileSync(join(dir, "brand-ui.manifest.json"), JSON.stringify(manifest));
  try {
    return body(dir);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

test("flat() normalizes an old-shape (pre-#86) manifest's types/otherExports without crashing", () => {
  withFixtureManifest(oldShapeManifest(), (dir) => {
    const manifest = loadManifest(dir);
    assert.ok(manifest, "loadManifest reads the checkout-local fixture manifest");

    let rows;
    assert.doesNotThrow(() => {
      rows = flat(manifest);
    }, "flat() does not throw on a manifest whose types/otherExports are bare strings");

    const typeRow = rows.find((r) => r.kind === "type" && r.pkg === "@elabs-ai/components-ui");
    assert.ok(typeRow, "a type row is produced from the old string-array bucket");
    assert.equal(typeRow.name, "ButtonProps", "the string entry's value becomes the row's name");
    assert.equal(
      typeof typeRow.name,
      "string",
      "name is a real string, not undefined — the exact crash trigger",
    );

    const exportRow = rows.find(
      (r) => r.kind === "export" && r.pkg === "@elabs-ai/components-ui" && !r.importPath,
    );
    assert.ok(exportRow, "an export row is produced from the old string-array bucket");
    assert.equal(exportRow.name, "createSelectionColumn");

    const subTypeRow = rows.find((r) => r.kind === "type" && r.importPath);
    assert.ok(subTypeRow, "a subpath type row is produced from the old string-array bucket");
    assert.equal(subTypeRow.name, "SubpathProps");

    const subExportRow = rows.find((r) => r.kind === "export" && r.importPath);
    assert.ok(subExportRow, "a subpath export row is produced from the old string-array bucket");
    assert.equal(subExportRow.name, "subpathHelper");

    // The exact call every reader of flat() makes (bin/brand-ui.mjs
    // search/docs, lib/mcp.mjs search/docs, lib/engine.mjs map) — must not throw.
    assert.doesNotThrow(() => {
      for (const r of rows) r.name.toLowerCase();
    }, "every row's name supports .toLowerCase() — the exact crash call site");
  });
});

test("flat() still handles the current {name, module} object shape unchanged", () => {
  withFixtureManifest(
    {
      name: "brand-ui",
      packages: {
        "@elabs-ai/components-ui": {
          path: "packages/ui",
          components: [],
          hooks: [],
          types: [{ name: "ButtonProps", module: "packages/ui/src/button/button.tsx" }],
          otherExports: [
            { name: "createSelectionColumn", module: "packages/ui/src/data-table.ts" },
          ],
        },
      },
    },
    (dir) => {
      const manifest = loadManifest(dir);
      const rows = flat(manifest);
      const typeRow = rows.find((r) => r.kind === "type");
      assert.equal(typeRow.name, "ButtonProps");
      assert.equal(typeRow.module, "packages/ui/src/button/button.tsx", "module is preserved");
    },
  );
});
