/** GENERATED by scripts/gen-community-themes.mjs from themes/ — do not edit. Run `pnpm gen`. */
import type { ThemeDefinition } from "@elabs-ai/components-tokens";

export const COMMUNITY_THEME_DEFINITIONS: readonly ThemeDefinition[] = [
  {
    value: "ocean-light",
    label: "Ocean Light",
    dark: false,
    family: "ocean",
    familyLabel: "Ocean",
  },
  { value: "ocean-dark", label: "Ocean Dark", dark: true, family: "ocean" },
];
