// GENERATED by scripts/gen-contract-tests.mjs — do not edit; re-run the generator instead.
/**
 * Contract probe for Gantt (`packages/charts/src/gantt/gantt.tsx`), derived from its
 * `Default` story (packages/charts/src/gantt/gantt.stories.tsx). See scripts/gen-contract-tests.mjs.
 */
import { describe, it, expect, afterEach } from "vitest";
import { render, cleanup } from "@testing-library/react";
import { createRef } from "react";
import * as stories from "../gantt/gantt.stories";
import knownFailuresJson from "../../../../scripts/check/contract-known-failures.json";

afterEach(cleanup);

// Every component here has its own prop/ref/element shape; a generated probe
// stays generic on purpose (loosely typed, not untyped — see
// scripts/gen-contract-tests.mjs) rather than re-deriving each one.
const KNOWN_FAILURES: Record<string, string> = knownFailuresJson;
const meta = stories.default as { component?: unknown; args?: Record<string, unknown> };
const Default = (stories as { Default?: { args?: Record<string, unknown> } }).Default;
// eslint-disable-next-line @typescript-eslint/no-explicit-any -- probe target; see comment above
const Component = meta.component as any;
const args = { ...(meta.args ?? {}), ...(Default?.args ?? {}) };
const isForwardRefComponent = Component?.["$$typeof"] === Symbol.for("react.forward_ref");

/** Wrap a known, tracked failure in `it.fails` so fixing it forces the key's removal. */
function contractIt(assertion: string, name: string, fn: () => void) {
  const key = `charts-gantt--default|jsdom|jsdom|${assertion}`;
  const reason = KNOWN_FAILURES[key];
  if (reason) return it.fails(`${name} (known failure: ${reason})`, fn);
  return it(name, fn);
}

describe("Gantt contract", () => {
  it.skipIf(!isForwardRefComponent)("forwards a ref to a DOM element", () => {
    const ref = createRef<Element>();
    render(<Component {...args} ref={ref} />);
    expect(ref.current).toBeInstanceOf(Element);
  });

  contractIt("className", "merges a caller className onto the root", () => {
    const { container } = render(<Component {...args} className="contract-probe" />);
    expect(container.querySelector(".contract-probe")).not.toBeNull();
  });

  contractIt("data-slot", 'exposes data-slot="gantt" on its root', () => {
    const { container } = render(<Component {...args} />);
    expect(container.querySelector('[data-slot="gantt"]')).not.toBeNull();
  });
});
