// GENERATED by packages/cli/scripts/gen-a2ui-catalog.mjs from
// packages/ai/src/a2ui/catalog.source.json (the `@elabs-ai/components-data` types) +
// brand-ui.manifest.json — do not edit; edit the source file and run `pnpm gen`.
import type { DataA2uiCatalogSchema } from "./types";

export const DATA_A2UI_CATALOG_SCHEMA: DataA2uiCatalogSchema = {
  AutoGrid: {
    children: false,
    props: {
      loading: {
        type: "boolean",
        description: "Rows are on their way: a layout-shaped skeleton.",
      },
      spec: {
        type: "object",
        required: true,
        description:
          "{ rows: object[], columns?: { key, label?, type?: text|number|date|boolean, format?: { style?: number|currency|percent, decimals?, currency?, abbreviate?, sign?: auto|always|parens, prefix?, suffix? }, aggregate?: sum|mean|median|min|max|count|uniqueCount, width?, pinned?: left|right, filter?: text|number|date|set|boolean|false, visual?: { kind: bar|heatmap, … } }[] (inferred from rows when absent), idKey?, title?, view?: GridState { version: 1, sorting?: {id,desc}[], columnFilters?: {id, value: {type:text|number|date, conditions:[{op, value?, to?, preset?}], join?} | {type:set, values:string[]} | {type:boolean, value}}[], columnVisibility?, grouping?: string[], columnPinning?: {left?, right?} }, mode?: grid|table, totals?: boolean, groupBy?: string[], floatingFilters?: boolean, height?: number }",
      },
    },
    events: {
      rowClick: "onRowClick",
    },
    source: "@elabs-ai/components-data",
    summary:
      "A data grid from ONE serializable DataGridSpec — rows, optional columns (inferred when absent) and an optional saved view. The table the agent should reach for: sort, filter, group, totals, copy and export built in.",
  },
};
