#!/usr/bin/env node
/**
 * debrand-scope.mjs — one-shot codemod. Kept as the audit record.
 *
 * Rewrote the npm scope and the repo-name token off the Qlik CoE EMEA identity:
 *
 *     @qlik-coe-emea/qlabs-components-   →  @elabs/components-
 *     @qlik-coe-emea                     →  @elabs
 *     qlabs-components                   →  elabs-components
 *
 * WHY: this repo is a private, unbranded fork. The directory was renamed to
 * `elabs-components` but nothing inside it knew — `elabs` appeared zero times in
 * 985 files. Nothing publishes any more (no remote, no registry), so the scope is
 * a free choice; `@elabs/components-*` matches the repo.
 *
 * THE RULE IS UNIFORM — the scope TOKEN is rewritten, not a list of package
 * names. This repo learned that the hard way in the previous rename
 * (`@brand/` → `@qlik-coe-emea/qlabs-components-`, see git history): a name map
 * renames the packages but leaves the executable prefix checks that drive the
 * gates, e.g.
 *
 *     check-dep-direction.mjs:  if (!name.startsWith("@qlik-coe-emea/")) continue;
 *
 * which leaves the dependency-DAG gate matching nothing and passing VACUOUSLY.
 * A silently dead gate is worse than a red one. There are 9 such prefix checks
 * plus 2 shell greps in `.claude/hooks/`. Rewriting the token keeps package
 * names, globs, doc placeholders, prefix checks and test fixtures consistent by
 * construction.
 *
 * ORDER MATTERS. `@qlik-coe-emea/qlabs-components-` CONTAINS `qlabs-components`,
 * so the scope forms must be rewritten before the bare repo-name form, or the
 * scope turns into `@qlik-coe-emea/elabs-components-`. The steps below run
 * longest-token-first for that reason.
 *
 * NOT rewritten, deliberately:
 *   - `Qlik-CoE-EMEA` (the GitHub org slug, 48 files / 93 occurrences). Those are
 *     URLs and `repository` fields that are being REMOVED, not renamed — this
 *     repo has no remote and does not publish. Rewriting them would mint
 *     plausible-looking URLs that resolve to nothing. Handled explicitly, with a
 *     decision per occurrence.
 *   - `light` / `dark` — the theme slugs. They move to `light`/`dark`
 *     in their own pass, together with the DTCG filenames, `$themes.json` modes
 *     and the `[data-theme]` selectors, so the rename is reviewable on its own.
 *   - Brand COPY ("Qlik Green", "Qlik Cloud", the wordmark, aria-labels). Prose a
 *     codemod would mangle; rewritten by hand.
 *   - bare `qlabs` with no `-components` — reported for a human to read, never
 *     guessed at.
 *   - pnpm-lock.yaml — regenerated by `pnpm install`, never text-patched.
 *   - node_modules / dist / release / storybook-static / .git / binaries.
 *
 * Re-running is a no-op: nothing matches the old tokens any more.
 *
 * Usage:  node scripts/debrand-scope.mjs [--dry-run]
 */
import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = dirname(dirname(fileURLToPath(import.meta.url)));

// Assembled from fragments so this file cannot rewrite its own constants if the
// skip-self guard below is ever removed. (The previous rename hit exactly that.)
const OLD_SCOPE = "@" + "qlik-coe-emea";
const OLD_REPO = "qlabs" + "-components";
const NEW_SCOPE = "@elabs";
const NEW_REPO = "elabs-components";

export const OLD = `${OLD_SCOPE}/${OLD_REPO}-`;
export const NEW = `${NEW_SCOPE}/components-`;

const DRY = process.argv.includes("--dry-run");

/**
 * Longest token first. Each entry is [needle, replacement]. Step 1 handles the
 * backslash-escaped form that appears inside regex literals (e.g.
 * check-intent-coverage.mjs's THIRD_PARTY_RE); missing it leaves a gate
 * asserting against the old name.
 */
const STEPS = [
  [`${OLD_SCOPE}\\/${OLD_REPO}-`, `${NEW_SCOPE}\\/components-`],
  [`${OLD_SCOPE}/${OLD_REPO}-`, `${NEW_SCOPE}/components-`],
  [OLD_SCOPE, NEW_SCOPE],
  [OLD_REPO, NEW_REPO],
];

const SKIP_DIRS = new Set([
  "node_modules",
  "dist",
  ".git",
  "release",
  "storybook-static",
  "coverage",
  ".turbo",
  "__output",
  ".next",
  "fonts",
  "retros",
  "research",
]);

// This file documents the rename, so its prose quotes the OLD tokens on purpose.
const SKIP_FILES = new Set(["pnpm-lock.yaml", "debrand-scope.mjs"]);
const TEXT_EXT = /\.(ts|tsx|js|jsx|mjs|cjs|json|md|mdx|css|yml|yaml|txt|sh|html)$/;

export function rewrite(text) {
  let out = text;
  for (const [needle, replacement] of STEPS) out = out.split(needle).join(replacement);
  return out;
}

/** Bare `qlabs` not followed by `-components` — reported, never rewritten. */
const BARE_CTX_RE = new RegExp(`.{0,40}qlabs(?!-components)[^\\n]{0,30}`, "gi");

function walk(dir, out = []) {
  for (const entry of readdirSync(dir)) {
    if (SKIP_DIRS.has(entry)) continue;
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full, out);
    else if (TEXT_EXT.test(entry) && !SKIP_FILES.has(entry)) out.push(full);
  }
  return out;
}

let files = 0;
let hits = 0;
const bare = [];

for (const file of walk(REPO_ROOT)) {
  const before = readFileSync(file, "utf8");
  if (!before.includes(OLD_SCOPE) && !before.includes(OLD_REPO)) continue;

  const after = rewrite(before);
  let n = 0;
  for (const [needle] of STEPS) n += before.split(needle).length - 1;

  if (after !== before) {
    hits += n;
    files++;
    if (!DRY) writeFileSync(file, after);
  }

  for (const m of after.match(BARE_CTX_RE) ?? []) {
    bare.push({ file: relative(REPO_ROOT, file), line: m.trim() });
  }
}

console.log(
  `${DRY ? "[dry-run] would rewrite" : "rewrote"} ${hits} occurrence(s) across ${files} file(s)`,
);
for (const [needle, replacement] of STEPS) console.log(`  ${needle}  →  ${replacement}`);

if (bare.length > 0) {
  console.log(`\n  ${bare.length} bare "qlabs" (no -components) left untouched — review:`);
  for (const b of bare.slice(0, 20)) console.log(`    ${b.file}\n      …${b.line}`);
  if (bare.length > 20) console.log(`    …and ${bare.length - 20} more`);
}

if (!DRY && hits > 0) console.log("\nNext: pnpm install, then the anti-vacuity checks.");
