#!/usr/bin/env node
/**
 * rename-scope.mjs — one-shot codemod, APPLIED. Kept as the audit record.
 *
 * Rewrote `@brand/` → `@qlik-coe-emea/qlabs-components-` across the repo
 * (4,683 occurrences in 758 files).
 *
 * WHY: GitHub Packages only accepts packages whose npm scope equals the
 * repository owner. `@brand` is a scope nobody owns, so these packages could
 * never publish under it. The owner is `Qlik-CoE-EMEA`, so the scope must be
 * `@qlik-coe-emea`; the name carries the repo so it stays collision-free inside
 * a scope shared by every repo in the org.
 *
 * THE RULE IS UNIFORM — the scope TOKEN is rewritten, not a list of package
 * names. A name map was tried first and was wrong: it renamed the packages but
 * left the executable prefix checks that drive the gates, e.g.
 *
 *     check-dep-direction.mjs:  if (!name.startsWith("@brand/")) continue;
 *
 * which would have left the dependency-DAG gate matching nothing and passing
 * vacuously. A silently dead gate is worse than a red one. Rewriting the token
 * keeps package names, globs (`@brand/*`), doc placeholders (`@brand/<pkg>`),
 * prefix checks and test fixtures consistent by construction.
 *
 * NOT rewritten, deliberately:
 *   - bare `@brand` with no slash — never the scope here. It is an agent mention
 *     (`@brand-ui-reviewer`), a design-token reference ("a @brand token"), or
 *     prose. Reported for a human to read, never guessed at.
 *   - CHANGELOG.md — released entries are history; v1.9.0 really did ship
 *     `@brand/ui`. The rename is noted under ## Unreleased instead.
 *   - .claude/retros/** — raw session transcripts, i.e. a historical log.
 *   - pnpm-lock.yaml — regenerated by `pnpm install`, never text-patched.
 *   - node_modules / dist / release / storybook-static / .git / binaries.
 *
 * Re-running is a no-op: nothing matches `@brand/` any more.
 *
 * Usage:  node scripts/rename-scope.mjs [--dry-run]
 */
import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = dirname(dirname(fileURLToPath(import.meta.url)));

// Assembled from fragments so this file cannot rewrite its own constants when
// the codemod runs over the repo that contains it (which is exactly what
// happened on the first run).
const OLD_SCOPE = "@" + "brand";
export const OLD = `${OLD_SCOPE}/`;
export const NEW = "@qlik-coe-emea/qlabs-components-";

const DRY = process.argv.includes("--dry-run");

const SKIP_DIRS = new Set([
  "node_modules",
  "dist",
  ".git",
  "release",
  "storybook-static",
  "coverage",
  ".turbo",
  "__output",
  ".next",
  "fonts",
  "retros",
]);
// This file documents the rename, so its prose quotes the OLD scope on purpose.
// Without skipping itself the codemod rewrites its own documentation — which is
// exactly what happened on the first run.
const SKIP_FILES = new Set(["CHANGELOG.md", "pnpm-lock.yaml", "rename-scope.mjs"]);
const TEXT_EXT = /\.(ts|tsx|js|jsx|mjs|cjs|json|md|mdx|css|yml|yaml|txt|sh|html)$/;

/**
 * Rewrite every form of the scope token, including the backslash-escaped one
 * inside regex literals (a gate test asserts on `/from "@brand\/ui"/`). Missing
 * that form leaves a test asserting against the old name.
 */
export function rewrite(text) {
  return text
    .split(`${OLD_SCOPE}\\/`)
    .join("@qlik-coe-emea\\/qlabs-components-")
    .split(OLD)
    .join(NEW);
}

/** Bare `@brand` not followed by `/` or `\` — reported, never rewritten. */
const BARE_CTX_RE = new RegExp(`.{0,40}${OLD_SCOPE}(?![/\\\\])[^\\n]{0,30}`, "g");

function walk(dir, out = []) {
  for (const entry of readdirSync(dir)) {
    if (SKIP_DIRS.has(entry)) continue;
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full, out);
    else if (TEXT_EXT.test(entry) && !SKIP_FILES.has(entry)) out.push(full);
  }
  return out;
}

let files = 0;
let hits = 0;
const bare = [];

for (const file of walk(REPO_ROOT)) {
  const before = readFileSync(file, "utf8");
  if (!before.includes(OLD_SCOPE)) continue;

  const after = rewrite(before);
  const n = before.split(OLD).length - 1 + (before.split(`${OLD_SCOPE}\\/`).length - 1);

  if (after !== before) {
    hits += n;
    files++;
    if (!DRY) writeFileSync(file, after);
  }

  for (const m of after.match(BARE_CTX_RE) ?? []) {
    bare.push({ file: relative(REPO_ROOT, file), line: m.trim() });
  }
}

console.log(
  `${DRY ? "[dry-run] would rewrite" : "rewrote"} ${hits} occurrence(s) across ${files} file(s)`,
);
console.log(`  ${OLD}  →  ${NEW}`);

if (bare.length > 0) {
  console.log(
    `\n  ${bare.length} bare "${OLD_SCOPE}" (no slash) left untouched — review, do not bulk-edit:`,
  );
  for (const b of bare.slice(0, 20)) console.log(`    ${b.file}\n      …${b.line}`);
  if (bare.length > 20) console.log(`    …and ${bare.length - 20} more`);
}

if (!DRY && hits > 0) console.log("\nNext: pnpm install, then the full gate battery.");
