/**
 * Charts / Recipes / River — the fifth River recipe (RM-126).
 *
 * A shots heatmap table with a hidden header. It lives in `apps/docs` rather
 * than beside the other four in `packages/charts/src/recipes/`, because the
 * picture is a `DataTable` from `@elabs-ai/components-data` and
 * `@elabs-ai/components-charts` must never import that package.
 *
 * The data is seeded and FICTIONAL: the original shot log is not public
 * domain, so the players and their tallies are invented, generated by a pure
 * function of the row and column index — never `Math.random`, so every render,
 * test and screenshot draws the same grid.
 */

import type { Meta, StoryObj } from "@storybook/react-vite";
import { expect, waitFor } from "storybook/test";
import { DataTable } from "@elabs-ai/components-data";
import type { ColumnDef } from "@elabs-ai/components-data";

/** Ten minute-buckets across a match, the columns of the grid. */
const BUCKETS = Array.from({ length: 10 }, (_, i) => `${i * 9 + 1}–${(i + 1) * 9}′`);

const PLAYERS = [
  "A. Vance",
  "M. Okoro",
  "L. Brandt",
  "R. Halim",
  "S. Duarte",
  "T. Nyström",
  "K. Ferreira",
  "J. Malik",
];

interface ShotRow {
  player: string;
  [bucket: string]: number | string;
}

/** A deterministic 0–1 wobble for the cell at (player, bucket). */
const wobble = (p: number, b: number) => (Math.sin((p + 1) * 12.9898 + (b + 1) * 78.233) + 1) / 2;

/** Shots per nine-minute bucket: a late-game lift, plus a deterministic wobble. */
const SHOTS: ShotRow[] = PLAYERS.map((player, p) => {
  const row: ShotRow = { player };
  BUCKETS.forEach((bucket, b) => {
    const lift = 1 + b / 6;
    row[bucket] = Math.round(lift * (1 + 6 * wobble(p, b)));
  });
  return row;
});

const shotsScale = { type: "stepped", steps: 5 } as const;

const shotColumns: ColumnDef<ShotRow>[] = [
  {
    accessorKey: "player",
    header: "Player",
    enableSorting: true,
    meta: { width: 22 },
  },
  ...BUCKETS.map<ColumnDef<ShotRow>>((bucket, b) => ({
    accessorKey: bucket,
    header: bucket,
    enableSorting: true,
    meta: {
      // Percent widths let the ten buckets shrink with the table instead of
      // flooring at their content width.
      width: 78 / BUCKETS.length,
      numeric: true,
      visual: {
        kind: "heatmap",
        scale: shotsScale,
        hideValue: true,
        // Every bucket shares ONE scale, so the key is printed once.
        legend: b === 0 ? "Shots per nine minutes" : false,
      },
    },
  })),
];

const meta = {
  title: "Charts/Recipes/River",
  parameters: {
    layout: "padded",
    docs: {
      description: {
        component:
          "The fifth River recipe: a shots heatmap table. Seeded, fictional data — the shapes are River’s, the numbers are ours.",
      },
    },
  },
} satisfies Meta;

export default meta;
type Story = StoryObj<typeof meta>;

/**
 * **Heatmap table, header hidden.** Props: `DataTable hideHeader` (the header
 * row collapses visually but its sort buttons still take focus),
 * `layout="auto"`, `density="compact"`, and a per-column `meta.visual` of
 * `{ kind: "heatmap", scale, hideValue: true }` sharing one stepped scale with
 * a single colour key. Under 450 px the table flips to one `<dl>` card per
 * player — the header was already hidden, so nothing is lost.
 */
export const HeatmapTableHiddenHeader: Story = {
  render: () => (
    <div className="w-full max-w-[900px]">
      <DataTable
        caption="Shots per nine-minute bucket, by player"
        columns={shotColumns}
        data={SHOTS}
        density="compact"
        getRowId={(row) => row.player}
        hideHeader
        layout="auto"
      />
    </div>
  ),
  play: async ({ canvasElement }) => {
    await waitFor(() =>
      expect(canvasElement.querySelectorAll('[data-slot="heatmap-cell"]').length).toBeGreaterThan(
        0,
      ),
    );
    const cards = canvasElement.querySelectorAll('[data-slot="data-table-card"]');
    const table = canvasElement.querySelector("table");
    if (cards.length > 0) {
      // Narrow: one card per player, and no <table> at all.
      await expect(cards).toHaveLength(PLAYERS.length);
      await expect(table).toBeNull();
    } else {
      // Wide: a real table whose header row is hidden, not removed.
      await expect(table).not.toBeNull();
      await expect(canvasElement.querySelectorAll('[data-slot="heatmap-cell"]')).toHaveLength(
        PLAYERS.length * BUCKETS.length,
      );
      // The header is hidden, not gone: the row still carries every label for
      // AT and its sort buttons still take focus — it simply draws no band.
      const thead = canvasElement.querySelector("thead");
      await expect(thead?.className).toContain("[&_th]:h-0");
      await expect(canvasElement.querySelector("thead th")).not.toBeNull();
    }
  },
};
