import { registerServiceLogos } from "@elabs-ai/components-icons";
// Vite JSON import (`resolveJsonModule`) — generated by `scripts/build-icon-index.mjs`
// (`icons:index`) from every file under `public/icons/<vendor>/`.
import index from "../../public/icons/index.json";

export interface IconIndexEntry {
  path: string;
  label: string;
  pack: string;
}

export type IconIndex = Record<string, IconIndexEntry>;

export interface IconPackSummary {
  pack: string;
  count: number;
}

const ICON_INDEX = index as IconIndex;

/** Every indexed icon, keyed `"vendor/name"` — the icon sheet and the YAML
 *  validator's (DG-09) unknown-name check both read this. */
export { ICON_INDEX };

/** Per-vendor counts derived from {@link ICON_INDEX}, sorted by pack name —
 *  drives the sidebar's "Icon packs" menu badges and the icon sheet's
 *  vendor filter. */
export const ICON_PACKS: IconPackSummary[] = Array.from(
  Object.values(ICON_INDEX)
    .reduce((counts, entry) => {
      counts.set(entry.pack, (counts.get(entry.pack) ?? 0) + 1);
      return counts;
    }, new Map<string, number>())
    .entries(),
)
  .map(([pack, count]) => ({ pack, count }))
  .sort((a, b) => a.pack.localeCompare(b.pack));

/**
 * Registers every vendored icon as a `ServiceLogo` mark, keyed `"vendor/name"`
 * (`registerServiceLogos`, `@elabs-ai/components-icons`). Call once, before
 * the app renders (`main.tsx`) — every `<ServiceLogo name="vendor/name" />`
 * in the app and the icon sheet resolves against this registry afterward.
 */
export function registerIconPacks(): void {
  registerServiceLogos(
    Object.fromEntries(
      Object.entries(ICON_INDEX).map(([key, entry]) => [
        key,
        { src: entry.path, label: entry.label },
      ]),
    ),
  );
}
