import { createElement } from "react";
import { registerServiceLogos, type ServiceLogoRender } from "@elabs-ai/components-icons";
import { VendorMark, type DarkMark } from "./theme-aware-mark";
// Vite JSON import (`resolveJsonModule`) — generated by `scripts/build-icon-index.mjs`
// (`icons:index`) from every file under `public/icons/<vendor>/`.
import index from "../../public/icons/index.json";

export interface IconIndexEntry {
  path: string;
  label: string;
  pack: string;
}

export type IconIndex = Record<string, IconIndexEntry>;

export interface IconPackSummary {
  pack: string;
  count: number;
}

const ICON_INDEX = index as IconIndex;

/** Every indexed icon, keyed `"vendor/name"` — the icon sheet and the YAML
 *  validator's (DG-09) unknown-name check both read this. */
export { ICON_INDEX };

/** Per-vendor counts derived from {@link ICON_INDEX}, sorted by pack name —
 *  drives the sidebar's "Icon packs" menu badges and the icon sheet's
 *  vendor filter. */
export const ICON_PACKS: IconPackSummary[] = Array.from(
  Object.values(ICON_INDEX)
    .reduce((counts, entry) => {
      counts.set(entry.pack, (counts.get(entry.pack) ?? 0) + 1);
      return counts;
    }, new Map<string, number>())
    .entries(),
)
  .map(([pack, count]) => ({ pack, count }))
  .sort((a, b) => a.pack.localeCompare(b.pack));

/** A vendor's dark-background variant, vendored next to its pack in `dark/` (outside
 *  `scripts/build-icon-index.mjs`'s reach, so it is never indexed as an icon of its own).
 *  Sources and dates: `THIRD_PARTY_ICONS.md`, "Dark-background variants". */
const darkVariant = (vendor: string, file: string): DarkMark => ({
  src: `/icons/${vendor}/dark/${file}`,
});

const AWS_DARK = darkVariant("aws", "aws.svg");
const CLICKHOUSE_DARK = darkVariant("clickhouse", "clickhouse.svg");
const DATABRICKS_DARK = darkVariant("databricks", "databricks.svg");
const QLIK_DARK = darkVariant("qlik", "qlik.svg");
const SNOWFLAKE_DARK = darkVariant("snowflake", "snowflake.svg");

/**
 * Vendor marks whose own ink vanishes on a dark surface (wave-2 review M6: 1.1–2.9:1 in
 * the legend, zone headers and nodes), plus the Microsoft marks (same failure, below). Each key is registered with a render callback
 * (`VendorMark`) instead of a bare `src`: `mono` becomes a `currentColor` mask in every
 * theme, and `brand` swaps to the vendor's dark variant in a dark theme. Every other
 * mark (the AWS/Azure/GCP service icons, the other packs) keeps its plain `src`.
 *
 * Several keys share one file: the DG-04 packs copy the vendor logo under product names
 * that have no mark of their own, so they share the vendor's dark variant too.
 */
const THEME_AWARE_MARKS: Record<string, DarkMark> = {
  "aws/aws": AWS_DARK,
  // Azure's blue clears 3:1 in the dark legends (3.9:1 dark, 3.0:1 qlik-dark) and no dark
  // variant was found: only its `mono` (grayscale, 2.0–3.0:1 in a zone header) needs the mask.
  "azure/azure": "keep",
  "clickhouse/clickhouse": CLICKHOUSE_DARK,
  "clickhouse/clickpipes": CLICKHOUSE_DARK,
  "databricks/databricks": DATABRICKS_DARK,
  "databricks/workspace": DATABRICKS_DARK,
  "databricks/unity-catalog": DATABRICKS_DARK,
  "databricks/delta": DATABRICKS_DARK,
  // Not in the review's list, but the same failure on the Qlik examples: SQL Server's grey
  // wordmark measured 1.9–2.9:1 on the dark nodes (`brand`) and 1.6–2.1:1 as `mono`.
  // No dark variant was vendored, so dark themes fall back to the mono mask.
  "microsoft/microsoft": "mono",
  "microsoft/sql-server": "mono",
  "qlik/qlik": QLIK_DARK,
  "qlik/cloud": QLIK_DARK,
  "qlik/data-gateway": QLIK_DARK,
  "qlik/sense-enterprise": QLIK_DARK,
  "qlik/answers": QLIK_DARK,
  "qlik/automate": QLIK_DARK,
  "qlik/automl": QLIK_DARK,
  // The Talend brand is retired into Qlik (talend.com redirects to qlik.com) and no dark
  // Talend mark was found, so dark themes fall back to the mono mask.
  "qlik/talend-cloud": "mono",
  "snowflake/snowflake": SNOWFLAKE_DARK,
  "snowflake/warehouse": SNOWFLAKE_DARK,
};

/**
 * Registers every vendored icon as a `ServiceLogo` mark, keyed `"vendor/name"`
 * (`registerServiceLogos`, `@elabs-ai/components-icons`). Call once, before
 * the app renders (`main.tsx`) — every `<ServiceLogo name="vendor/name" />`
 * in the app and the icon sheet resolves against this registry afterward.
 */
export function registerIconPacks(): void {
  registerServiceLogos(
    Object.fromEntries(
      Object.entries(ICON_INDEX).map(([key, entry]) => {
        const dark = THEME_AWARE_MARKS[key];
        if (!dark) return [key, { src: entry.path, label: entry.label }];
        // P4: library gap — `ServiceLogo`'s `mono` only desaturates a `src` image
        // (service-logo.tsx:126), and a definition has no dark variant. With `mono` as a
        // `currentColor` mask and an optional `srcDark` picked through
        // `resolveThemeIsDark`, this callback becomes `{ src, srcDark, label }`
        // (DG-05-node-primitives.md, "Wave-2 review additions").
        const render: ServiceLogoRender = ({ size, variant }) =>
          createElement(VendorMark, { src: entry.path, dark, size, variant });
        return [key, { render, label: entry.label }];
      }),
    ),
  );
}
